### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by anders-wiggers** [Jungwoo-An/react-editor-js#1]
When I try to use the editor I get a ReferenceError: window is not defined.

I follow your codebox example, but with no luck.

I use React with Next.js

**Comment by shubhsherl** [comment]
@anders-wiggers here is something for you: https://github.com/zeit/next.js/wiki/FAQ#i-use-a-library-which-throws-window-is-undefined

**Comment by Jungwoo-An** [comment]
@anders-wiggers  Thank your interest. and sorry my answer too late.
This component is browser only and is not available in ssr. I think you should use no-ssr.

**Comment by asmsuechan** [comment]
FYI, this is my workaround to use this library in my next.js project.

```typescript
import { FunctionComponent } from 'react';

interface ComponentProps {
  title: string;
}

const Component: FunctionComponent<ComponentProps> = (props: ComponentProps) => {
  const { title } = props;

  const EditorComponent: FunctionComponent = () => {
    const EditorJs = require('react-editor-js');
    const { EDITOR_JS_TOOLS } = require('@/lib/editor-tool');
    return (<EditorJs data={data} tools={EDITOR_JS_TOOLS} />)
  }

  return (
    <div>
      <span>{title}</span>
      { window && (<EditorComponent />) }
    </div>
  );
}

export default Component;
```

**Comment by danilockthar** [comment]
Im using Dynamic import in next and works great at first glance.

**Comment by VityaSchel** [comment]
> @anders-wiggers here is something for you: https://github.com/zeit/next.js/wiki/FAQ#i-use-a-library-which-throws-window-is-undefined

Where can I read this article now? Looks like broken link

**Comment by edonadei** [comment]
FYI if you're being stuck here, the solution I found to use react-editor-js with Next is:

1. Create your component using react-editor-js, here we're going to call it **Editor.js**

```jsx
import React, { useState } from "react";
import { EDITOR_JS_TOOLS } from "../lib/editorjstools";
import EditorJs from "react-editor-js";

export const Editor = () => {
  const [content, setContent] = useState({}); // Init this hook with normal data
  return (
    <div>
      <EditorJs data={content} tools={EDITOR_JS_TOOLS} />
    </div>
  );
};

export default Editor;
```

2. Import it dynamically with Next in your other component

```jsx
import dynamic from 'next/dynamic'

const EditorJsWithNoSSR = dynamic(() => import("./Editor"), {
  ssr: false,
});

export default function Article() {
  return (
    <div className="relative py-16 bg-white overflow-hidden">
      <EditorJsWithNoSSR />
    </div>
  );
}

```

**Comment by mrsaifullah52** [comment]
> ### FYI if you're being stuck here, the solution I found to use react-editor-js with Next is
> 1. Create your component using react-editor-js, here we're going to call it **Editor.js**
> 
> ```js
> import React, { useState } from "react";
> import EditorJs from "react-editor-js";
> 
> export const Editor = () => {
>   const [content, setContent] = useState({}); // Init this hook with normal data
>   return (
>     <div>
>       <EditorJs data={content} tools={EDITOR_JS_TOOLS} />
>     </div>
>   );
> };
> 
> export default Editor;
> ```
> 
> 2. Import it dynamically with Next in your other component
> 
> ```js
> import dynamic from 'next/dynamic'
> 
> const EditorJsWithNoSSR = dynamic(() => import("./Editor"), {
>   ssr: false,
> });
> 
> export default function Article() {
>   return (
>     <div className="relative py-16 bg-white overflow-hidden">
>       <EditorJsWithNoSSR />
>     </div>
>   );
> }
> ```
> 
> Now it should work

not working

> error: Cannot read properties of undefined (reading 'then')

**Comment by hassanah07** [comment]
not working. please solve this error
