### ISSUE TITLE
editorInstance.render() gives error

### ISSUE THREAD

**Issue by allnichols** [Jungwoo-An/react-editor-js#10]
When pulling saved data from my database this.editorInstance.render() gives an "cannot read property of map undefined". Would you have insight into this error?

**Comment by Jungwoo-An** [comment]
@allnichols Hi! Thanks for using this library 😍 

Did you solve the issue?

**Comment by allnichols** [comment]
Yes I did!

**Comment by allnichols** [comment]
I'm having trouble getting the image tool to work properly. I can upload the image but can't seem to get it to populate when I reload the editor. Also the output data shows an empty file object.

**Comment by Jungwoo-An** [comment]
@allnichols 

You probably didn't set option of image tool. refer to [here](https://github.com/editor-js/image#usage).

Thanks!
