### ISSUE TITLE
Word counter and Reading time for the written text.

### ISSUE THREAD

**Issue by SohaibShafiq1** [Jungwoo-An/react-editor-js#101]
Can we calculate total number of words in editor.js(all blocks)

**Comment by Jungwoo-An** [comment]
@SohaibShafiq1 Hi! First of all, thanks for your interest! 👋 

There is no official way. However, you can obtain number of words from saved block.

```ts
const totalReadingTime = blocks.filter(block => block.type === 'paragraph').reduce((result, block) => result + getReadingTime(block.data.text), 0);
```

Thanks!
