### ISSUE TITLE
@editorjs/image, "Can't upload image. Please try another." Error 404

### ISSUE THREAD

**Issue by JPEdgar** [Jungwoo-An/react-editor-js#102]
### Environment

installed today (2/26/2021)

### Describe
npm commands...
`npm i react-editor-js @editorjs/image`

```
import Image from "@editorjs/image";
function App () {
  const EDITOR_JS_TOOLS = {
    image: Image,
  };
  return ( <EditorJs tools={EDITOR_JS_TOOLS} /> )
}
```

At first glance, the program works precisely how I wanted it to.  But when I went to insert an image, after a moment of almost working and I can see the image, I got an error bubble on the bottom-left that reads, "Couldn't upload image. Please try another."  In the console, "POST HTTP://localhost:3000/ 404 (Not Found)" and, "Image Tool: uploading failed because of" and a body object.  See the attached screenshot for as much detail I can find.
![404 image](https://user-images.githubusercontent.com/70185831/109372673-a88d7080-785f-11eb-82a8-43a8a8c42a2b.PNG)

**Comment by Jungwoo-An** [comment]
Duplicate of #97

**Comment by Uttkarsh09** [comment]
Any updates on the issue?

**Comment by iftekharriyad** [comment]
Please someone solve this issue. Image is a critical part of any rich text editors.

**Comment by Jungwoo-An** [comment]
@Uttkarsh09 @iftekharriyad This issue is not bug. editor-js is working correctly. Please explain in more detail.

**Comment by iftekharriyad** [comment]
Couldn't upload an image from the local drive.

![Screenshot_2021-03-21_23-54-38](https://user-images.githubusercontent.com/52159538/111917431-31d44380-8aaa-11eb-864f-c29a96883abc.png)

**Comment by Jungwoo-An** [comment]
Thanks! Did you set uploader option of image plugin? [Ref](https://github.com/Jungwoo-An/react-editor-js/issues/97#issuecomment-772134851)

**Comment by iftekharriyad** [comment]
Oh! Do I have to! I didn't modify the code from the codesandbox. I will try to set the uploader option of the image plugin and see if it will work or not.

**Comment by Jungwoo-An** [comment]
@iftekharriyad Yes. By default, editor-js does not support image upload server.

**Comment by atlas700** [comment]
i have worse than yours!
Image Tool: uploading failed because of Error: An error occured when running the middleware for the imageUploader route
    at UploadThingError.fromResponse
