### ISSUE TITLE
TypeError: n.closest is not a function [Nextjs]

### ISSUE THREAD

**Issue by duxcodes** [Jungwoo-An/react-editor-js#104]
### Environment

- @editorjs/editorjs version: ^2.19.1
- react-editor-js version: ^1.9.0
- Nextjs version: ^10.0.6

### Describe

I am having trouble deleting the block as it gets deleted but leaves error. It happens sometimes only (check the video as it didn't happen first time)

Please check the screen recording attached.

Also feel free to ask for code in case needed.

**Screen Video:**
https://user-images.githubusercontent.com/62444082/110236467-fdb23c00-7f5b-11eb-8450-10b0161ed527.mov

**Comment by Jungwoo-An** [comment]
Ref https://github.com/codex-team/editor.js/issues/1317
