### ISSUE TITLE
embed not working

### ISSUE THREAD

**Issue by js-ts** [Jungwoo-An/react-editor-js#106]
### Environment

  "@editorjs/checklist": "^1.3.0",
    "@editorjs/code": "^2.6.0",
    "@editorjs/delimiter": "^1.2.0",
    "@editorjs/editorjs": "^2.19.1",
    "@editorjs/embed": "^2.4.0",
    "@editorjs/header": "^2.6.1",
    "@editorjs/image": "^2.6.0",
    "@editorjs/inline-code": "^1.3.1",
    "@editorjs/link": "^2.3.1",
    "@editorjs/list": "^1.6.2",
    "@editorjs/marker": "^1.2.2",
    "@editorjs/paragraph": "^2.8.0",
    "@editorjs/quote": "^2.4.0",
    "@editorjs/raw": "^2.3.0",
    "@editorjs/simple-image": "^1.4.0",
    "@editorjs/table": "^1.3.0",
    "@editorjs/warning": "^1.2.0",
   "react-editor-js": "^1.9.0",

### Describe
iframe doesn't work on my package versions if I paste iframe tag into the editor it just show the text and not the embeded iframe

embed not working link codesandbox [not working](https://codesandbox.io/s/react-editor-js-forked-zxeu3)
embed working but older version  codesandbox [working](https://codesandbox.io/s/23opz?file=/index.js)

you can paste this for testing-
```
<iframe height="265" style="width: 100%;" scrolling="no" title="GLSL Sample027" src="https://codepen.io/Web_yuki1027/embed/yLgYpWM?height=265&theme-id=light&default-tab=js,result" frameborder="no" loading="lazy" allowtransparency="true" allowfullscreen="true">
  See the Pen <a href='https://codepen.io/Web_yuki1027/pen/yLgYpWM'>GLSL Sample027</a> by Yuki
  (<a href='https://codepen.io/Web_yuki1027'>@Web_yuki1027</a>) on <a href='https://codepen.io'>CodePen</a>.
</iframe>
```

instead of embeding on pasting it just pastes the code

*this issue to me is partially resolved even though pasting a single link is much more convenient but it limits the number of sites from which you can embed it's much better to use <iframe> instead of a link

**Comment by Jungwoo-An** [comment]
@js-ts Hi! First of all, thanks for your interest! 👋 

Editor-js is block based editor. If you want to use embed, create new tools.

Thanks!
