### ISSUE TITLE
Export props types of component

### ISSUE THREAD

**Issue by anatolyefimov** [Jungwoo-An/react-editor-js#110]
It would be great to get the type of props `EditorJs`. I cannot get them through `React.ComponentProps`. Could you export this type?

**Comment by Jungwoo-An** [comment]
@anatolyefimov Hi! First of all, thanks for your interest! 👋 

You can import type named Props. example is below

```ts
import { Props } from 'react-editor-js';
```

Thanks!

**Comment by anatolyefimov** [comment]
Sorry, i am pretty sure  i can't import like this, i suppose need export from `index.ts`

**Comment by Nekaravaev** [comment]
Currently, it's works with 

`import type { Props } from "react-editor-js/dist/EditorJs";`

https://github.com/Jungwoo-An/react-editor-js/blob/8a3a924bab74b54ffe58d837f5a8011ecce11e76/lib/EditorJs.tsx#L19

**Comment by Jungwoo-An** [comment]
I'm sorry I'm so late.

#131 PR is included in version 1.10.0
