### ISSUE TITLE
Cannot read property 'holder'/'tool' of undefined

### ISSUE THREAD

**Issue by fkocovski** [Jungwoo-An/react-editor-js#113]
### Environment

- @editorjs/editorjs version: 2.20.2
- react-editor-js version: 1.9.0

### Describe

When trying to manually render data with `onReady`, I keep getting following error

![image](https://user-images.githubusercontent.com/9000611/115527957-dd330c80-a291-11eb-8231-3960c401f50e.png)

Code looks as follows

```
<EditorJs
        onReady={(instance) => instance.render({ blocks: [] })}
        tools={EDITOR_JS_TOOLS}
        instanceRef={(instance) => (editor.current = instance)}
      />
```

Tried both with and without `enableReInitialize` as well as with `useEffect`

Please note: with `2.19.3` only the first error appears `Uncaught TypeError: Cannot read property 'holder' of undefined` but afterwards it is possible to focus the editor

**Comment by Jungwoo-An** [comment]
Ref https://github.com/codex-team/editor.js/issues/1669
