### ISSUE TITLE
Randomly creating duplicate blog

### ISSUE THREAD

**Issue by cjmling** [Jungwoo-An/react-editor-js#114]
### Environment

- @editorjs/editorjs version: ^2.21.0
- react-editor-js version: ^1.9.0

### Describe

First of all I have to tell , I tried hard to create reproduceable bugs in sandbox, but whatever I tried I can't reproduce it.
I spend like half day just to try to debugging this but still no luck. A help will be very appreciated.

I feel it must have to do something with `useEffect`.  

Whenever I tried to update a property of blog ( title or category or tags ), then `useEffect` fire, and then at sometime the editor is duplicated. 

As in the gif below you will see the bugs.  And relevant codes are

**EditorJS**
```
<EditorJs
      instanceRef={instance => (instanceRef.current = instance)}
      tools={EDITOR_JS_TOOLS}
      data={{
          time: 1556098174501,
          blocks: blogContent
      }}
      enableReInitialize={true}
  />
```

**blogContent**
`const [blogContent, setBlogContent] = useState<any[]>([]);`

**Tags Input:**
```
<Select mode="tags" value={blog?.tags} style={{ width: '100%' }} placeholder="Tags Mode" onChange={handleTagsChanged}>
     { Configs.blogTags.map((tag) => <Option key={tag} value={tag}>{tag}</Option>) }
</Select>
```

**handleTagsChanged**
```
const handleTagsChanged = (values: any) => {
        const updatedBlog = {...blog};
        updatedBlog.tags = values;

        setBlog(updatedBlog);
}
```

**setBlog**
`const [blog, setBlog] = useState<Blog>();`

**useEffect**
```
React.useEffect(() => { 
        saveBlog();
}, [blog]);
```

**saveBlog**
```
async function saveBlog(saveType = 'draft') {
        console.log('saveblog', blog?.content);
        const savedBlog = await Request.post(`/blog`, {blog: blog, saveType: saveType});
 }
```

![I1S7x4COto](https://user-images.githubusercontent.com/1612187/116811580-5b39c200-ab74-11eb-8f9e-6034cccef3fe.gif)

**Comment by cjmling** [comment]
If it matter I also load my blog async as well

```
async function loadBlog(id: string) {
      const loadedBlog = await Request.get(`/blog/${id}`);
      setBlog(loadedBlog);
      setBlogContent(loadedBlog.content);
  }
```
```
React.useEffect(() => {
    if (params.id) {
        loadBlog(params.id);
    }
}, [params])
```

**Comment by cjmling** [comment]
@Jungwoo-An  If I don't use enableReInitialize prop

When I load the editor blocks asynchronously (via useEffect), it won't set the blocks on page load.

**Comment by Jungwoo-An** [comment]
@cjmling Oh, I'm sorry. I mistake. I'll check it.

**Comment by christoph-kluge** [comment]
@cjmling you may use a check before you load the editor. In such a case it's initialized properly
```
{blogContent && <EditorJs key={'editor-js-' + blog.id}
                          data={blogContent}
                          tools={EDITOR_TOOLS}
/>}
```

**Comment by cjmling** [comment]
@christoph-kluge I tried your code, without `enableReInitialize`, it won't set blocks once loaded from DB.

**Comment by Jungwoo-An** [comment]
I close this issue. If you have anything more to say, plz reopen issue.

Thanks!
