### ISSUE TITLE
Can you give some example of how to fetch entered data?

### ISSUE THREAD

**Issue by sabit990928** [Jungwoo-An/react-editor-js#12]
I tried your example with instance in documentation, but undefinded also when I console.log data in onChange function. Can you give some real example of fetching data? Thanks

**Comment by sabit990928** [comment]
Maybe it will help someone)
```
  handleCustomSave = async () => {
    const savedData = await this.ref.save()
    console.log('saved: ', this.ref, savedData)
  }

  saveInstance = ref => {
    this.ref = ref
  }

  render() {
    return (
      <>
        <EditorJs
          placeholder="Let`s write an awesome story!"
          autofocus
          instanceRef={this.saveInstance}
          minHeight={100}
     ...
```

**Comment by Jungwoo-An** [comment]
@sabit990928 Wow! First of all, thanks for your interest! 😍

I think you solved this problem, but if it happens again, can you give me reproduce link?

Thanks! 👍

**Comment by sabit990928** [comment]
Thanks, @Jungwoo-An. Do you have any idea how to show data without edit mode? 
There is a kind of teacher-student connection in my app. So the teacher can create some content, a student should see formatted content

**Comment by Jungwoo-An** [comment]
@sabit990928 Editor JS makes easy to implement the same formatted content in any language with data blocks. Therefore, data blocks in the web environment need to be converted to html code. looks like [this](https://repl.it/@GodwinOnimisi/heloo) ([Ref](https://github.com/codex-team/editor.js/issues/676))

Thanks!

**Comment by sabit990928** [comment]
@Jungwoo-An, reference that you said work well, but there is no condition for embed case
Do you have any idea how to convert them? 

I also find realization for Angular
`   
                    <div *ngSwitchCase="'embed'">
                        <div class="cdx-block embed-tool">
                            <iframe class="embed-tool__content" style="width:100%;" height="320" frameborder="0"
                                allowfullscreen [src]="b?.data?.embed | safe : 'resourceUrl'"></iframe>
                            <div style="text-align: center; margin-top: 5px;" [innerHTML]="b?.data?.caption"></div>
                        </div>
                    </div>`

**Comment by sabit990928** [comment]
Sorry for disturbing)
Maybe it helps someone

`            <iframe class="embed-tool__content" style="width:100%;" height="320" frameborder="0"
            allowfullscreen src=${obj.data.embed}></iframe>
`
