### ISSUE TITLE
Error rendering an instance of react-editor-js with default or with string holder prop.

### ISSUE THREAD

**Issue by trc485** [Jungwoo-An/react-editor-js#120]
### Environment
Create react app
react-scripts: 3.4.4
react: 16.9
react-dom: 16.14.0
node: v12.18.3

- editorjs/editorjs": 2.19.1,
- react-editor-js 1.9.0

### Describe
Error rendering an instance of react-editor-js with with a string holder prop.
It works only by specifying holder with a custom element.
Is this a bug or is it something I am doing wrong?

```javascript
import ReactEditorJS from 'react-editor-js';
{/* return react-editor-js from inside function component*/}
  return (
    <ReactEditorJS
      instanceRef={setEditorInstanceRef}
      onChange={updateBlocks}
      tools={EDITOR_JS_TOOLS}
      data={data}
      holder="editor-js"
    />
  );
```
returning a ReactEditorJS instance from your package, with string holder prop, throws the following errors:
Editor.js is not ready because of Error: element with ID «editor-js2» is missing. Pass correct holder's ID.
Uncaught (in promise) Error: element with ID «editor-js2» is missing. Pass correct holder's ID.

I inspected the DOM in the console, and here is the div that is generated. A random appendix gets attached to the default id?
Also this default id is not same as editorjs package, which I suppose is "editorjs".

```html
<div id="editor-js-kov9xcoe"></div>
``` 

Anyway I was able to make it work only by following documentation for "using custom element"

```javascript
import ReactEditorJS from 'react-editor-js';
{/* return react-editor-js from inside function component*/}
  return (
    <ReactEditorJS
      instanceRef={setEditorInstanceRef}
      onChange={updateBlocks}
      tools={EDITOR_JS_TOOLS}
      data={data}
      holder="editor-js"
    >
      <div id="editor-js" />
    </ReactEditorJS>
  );
```
Am I missing something or is this a bug?

Thank you in advance for the attention

**Comment by Jungwoo-An** [comment]
@trc485 Hi! First of all, thanks for your interest! 👋 

By default, holder is randomly string. If you want to set custom holder, You must follow readme solution. (react-editor-js does not create element by holder prop. For identification purpose only. If necessary, feel free to submit pr.)

Thanks!
