### ISSUE TITLE
Infinite OnChange when use with react hook form

### ISSUE THREAD

**Issue by huuhunghienhoa** [Jungwoo-An/react-editor-js#123]
### Environment
Demo: 

https://codesandbox.io/s/react-hook-form-v7-controller-forked-e0rk5?file=/src/Editor.js

- @editorjs/editorjs version: 2.22.0
- react-editor-js version: 1.9.0

### Describe
When i use editorjs with react hook form. 
I need editor data change when setValue form. 
At example: https://codesandbox.io/s/react-hook-form-v7-controller-forked-e0rk5?file=/src/Editor.js

I want when i click "Set to editorjs". "Set ne" data will show in ediorjs. 

I set enableReInitialize to true,  it seems like the 'onChange' is triggered infinitely.

**Comment by Jungwoo-An** [comment]
@huuhunghienhoa Hi! First of all, thanks for your interest! 👋 

Thanks!
