### ISSUE TITLE
does not work with @editorjs/editorjs ver.2.22.0

### ISSUE THREAD

**Issue by yhiguchi-concerto** [Jungwoo-An/react-editor-js#126]
### Environment

- @editorjs/editorjs version: 2.22.0
- react-editor-js version: 1.9.0

### Describe

may not be a bug, but the current version seem not working with @editorjs/editorjs ver. 2.22.0 and after.
on my VSCode, the error message appears on 'onChange' as follows  - 
Overload 1 of 2, '(props: Props | Readonly<Props>): EditorJsContainer', gave the following error.
    Type '(api: API, newData?: OutputData | undefined) => void' is not assignable to type '((api: API, block: BlockAPI) => void) & ((api: API, data?: OutputData | undefined) => void)'.
      Type '(api: API, newData?: OutputData | undefined) => void' is not assignable to type '(api: API, block: BlockAPI) => void'.
        Types of parameters 'newData' and 'block' are incompatible.
          Property 'blocks' is missing in type 'BlockAPI' but required in type 'OutputData'.
  Overload 2 of 2, '(props: Props, context: any): EditorJsContainer', gave the following error.
    Type '(api: API, newData?: OutputData | undefined) => void' is not assignable to type '((api: API, block: BlockAPI) => void) & ((api: API, data?: OutputData | undefined) => void)'.
      Type '(api: API, newData?: OutputData | undefined) => void' is not assignable to type '(api: API, block: BlockAPI) => void'.ts(2769)

should I use ver. 2.19.1 ?

**Comment by Jungwoo-An** [comment]
@yhiguchi-concerto Hi! First of all, thanks for your interest! 👋 

It works fine in my environment. Could you provide me reproduce link? (Github, Codesandbox, ...)

Thanks!
