### ISSUE TITLE
How to remove sanitizing html tags in onChange jsx property

### ISSUE THREAD

**Issue by VladimirTambovtsev** [Jungwoo-An/react-editor-js#128]
I need to get written html tags in onChange property without escaping special characters: '<', '>', etc.
```ts
onChange={(api: API, outputData: OutputData | undefined) => {
    console.log(outputData?.blocks);
}}


```
So for now I get:
```txt
"Some text here &lt;mark class=\"cdx-marker\"&gt;and tag that should not remove special characters here&lt;/mark&gt;"
```
instead of text that was typed in paragraph:
```txt
Some text here <mark class=\"cdx-marker\">and tag that should not remove special characters here</mark>
```

How can I do that?
Thanks

**Comment by Jungwoo-An** [comment]
@VladimirTambovtsev Hi! First of all, thanks for your interest! 👋 

I think [this link](https://editorjs.io/sanitizer) will help you.

Thanks!

**Comment by Jungwoo-An** [comment]
Could you provide me reproduce link? (Github, Codesandbox, ...)
