### ISSUE TITLE
Using the sanitizer

### ISSUE THREAD

**Issue by ramiel** [Jungwoo-An/react-editor-js#129]
### Environment

- @editorjs/editorjs version: 2.22.1
- react-editor-js version: 1.9.0

### Describe

The EditorJS component accept a prop called `sanitizer` and I'm expecting data to be sanitized with that configuration, but nothing is happening. How am I suppose to use the sanitizer?

**Comment by Jungwoo-An** [comment]
@ramiel Hi! First of all, thanks for your interest! 👋 

It works fine in my environment. Could you provide me reproduce link? (Github, Codesandbox, ...)

Thanks!

**Comment by ramiel** [comment]
You can check this [https://codesandbox.io/s/dark-night-n3yiv?file=/src/App.js](https://codesandbox.io/s/dark-night-n3yiv?file=/src/App.js)

There's already some content, but try to just add a new link. I'm expecting the link to have target `_blank`, but it doesn't. 
It also looks like the sanitizer is not called at all.

**Comment by Jungwoo-An** [comment]
@ramiel In my opinion, default sanitizer config is still implementing. 😢 (sanitizer config does not exist in the document)

**Comment by ramiel** [comment]
So you mean that nothing happens because editorjs does nothing? In this case I may have misunderstood how to use it

**Comment by Jungwoo-An** [comment]
Yes. I think you used it correctly.
