### ISSUE TITLE
Why do we save Plugins in devDependencies?

### ISSUE THREAD

**Issue by wmonecke** [Jungwoo-An/react-editor-js#133]
First of all: Awesome package! 

I just wanted to know if it was a typo or why should we save Plugins in dev dependencies?

**Comment by Jungwoo-An** [comment]
@wmonecke Hi! First of all, thanks for your interest! 👋 

It's a typo. I'll fix asap.

Thanks!

**Comment by wmonecke** [comment]
@Jungwoo-An Thank you for your hard work! :)
