### ISSUE TITLE
How do I use onCompareBlocks?

### ISSUE THREAD

**Issue by wmonecke** [Jungwoo-An/react-editor-js#134]
Hi there!

I am a bit stuck on this method. What do I need to return from it? a Boolean value? :)

EDIT: Yes it is a boolean. However, it doesnt seem to work when `enableReInitialize` is set to true. The editorjs doesnt seem to initialize at all.

**Comment by Jungwoo-An** [comment]
I'm sorry for the late response. This issue will be fixed in v2.

v1 enableReInitialize props is used only for re-rendering data.
