### ISSUE TITLE
Add placeholder to line created programmatically 

### ISSUE THREAD

**Issue by sethmichaelbrown** [Jungwoo-An/react-editor-js#135]
Hello - thanks for creating this wrapper for EditorJS. It has been great to work with so far. I would like to create a template option for users that would allow for a button click to populate a header and paragraph. I would like to be able to populate variable placeholders for the new paragraph lines. Would it be possible to do something like this? I read through the issue linked in this repo to the EditorJS docs regarding setting a single placeholder via the tools config - just wanted to note this request is different from that behavior. Thank you!

**Comment by Jungwoo-An** [comment]
I'm sorry for the late response. You can create template. react-editor-js respects the default behavior of editor-js.

**Comment by Jungwoo-An** [comment]
I close this issue. If you have anything more to say, plz reopen issue.

Thanks!

**Comment by sethmichaelbrown** [comment]
Thank you, @Jungwoo-An
