### ISSUE TITLE
How to use the Parent's container width instead of EditorJS width?

### ISSUE THREAD

**Issue by papunmohanty** [Jungwoo-An/react-editor-js#139]
### Environment

- @editorjs/editorjs version: 2.22.2
- react-editor-js version: 1.10.0

### Describe
How to use the parent's width instead of the EditorJS's own width?
In below Image, can be seen that in the form's input element I am using the Editor JS component and it is having it's own width.

![EditorJS_container_issue](https://user-images.githubusercontent.com/10744913/131211937-04670f0e-6b22-4dfa-8fb4-013d59e92bf6.png)

**Comment by papunmohanty** [comment]
Here is the code snippet 
`import React from 'react'
import EditorJs from 'react-editor-js'
import ImageTool from '@editorjs/image';
import { EDITOR_JS_TOOLS } from './tools'
import { Button } from '@material-ui/core'
import { useState } from 'react';


const AddBlog = () => {

  const [blogContent, setBlogContent] = useState({})

  return (
    <div className="ui main">
      <h2>Add Blog</h2>
      <form className="ui form">
        <div className="field">
          <label>Blog Name</label>
          <input type="text" name="name" placeholder="Blog Name"/>
        </div>
        <div className="field">
          <label>Blog Content</label>
          <EditorJs
            onChange={(_, newData) => setBlogContent(JSON.stringify(newData))}
            holder="custom"
            tools={
              {
                imageTool: {
                  class: ImageTool,
                  config: {
                    endpoint : 'http://127.0.0.1:5000/im_size',
                  }
                }
              },
              EDITOR_JS_TOOLS
            }
          >
              <div id="custom"/>
          </EditorJs>
        </div>
        <Button color="primary" variant="contained" onClick={ () => console.log(blogContent) } className="ui button blue">Add</Button>
      </form>
    </div>
  )
}

export default AddBlog
`

**Comment by Jungwoo-An** [comment]
@papunmohanty Hi! First of all, thanks for your interest! 👋 

You can use custom style for holder element. `<div id="custom" style="width: 100%;">`

Thanks!
