### ISSUE TITLE
problem with updating the editor content

### ISSUE THREAD

**Issue by mohanagy** [Jungwoo-An/react-editor-js#14]
I have notes list and I have an editor and I'm trying to update the content of the editor depending on the user selection,
so if he selects the first note the editor will change the content to the first note and if the user selects the second one the content will change to second note content and goes on.
I faced two problems,
the first one if I set initial  data and the user selects a note, the content never changes,
then I thought I must enable this option `enableReInitialize` but I got this error `Uncaught (in promise) TypeError: _this.instance.destroy is not a function
`
so did I miss something?

this is my code 
![code](https://user-images.githubusercontent.com/11216054/71753737-2d634100-2e8c-11ea-81b2-f1957fc31884.png)

**Comment by Jungwoo-An** [comment]
@mohanagy Hi! First of all, thanks for your interest! 😍

I'll check it asap.

Thanks!

**Comment by cuongdevjs** [comment]
yeah, exactly. Data state never effects in useEffect? Can you check it soon?

**Comment by Jungwoo-An** [comment]
@mohanagy 

Hi! I have solved this issue and published! (v1.4.2, Rel: #15 )

Thanks! ❤️

**Comment by mohanagy** [comment]
Awsome !
