### ISSUE TITLE
hyper link not changing 

### ISSUE THREAD

**Issue by vishal-kushwaha-itorix** [Jungwoo-An/react-editor-js#141]
when I'm trying to update the hyperlink it's not working

https://user-images.githubusercontent.com/85753351/131970819-dbac58a8-0f12-461c-a3fa-8086f210573e.mov

**Comment by Jungwoo-An** [comment]
@vishal-kushwaha-itorix Hi! First of all, thanks for your interest! 👋 

Which editor version are you using?

Thanks!

**Comment by vishal-kushwaha-itorix** [comment]
latest 1.10

**Comment by Jungwoo-An** [comment]
@vishal-kushwaha-itorix That's version of react-editor-js. Please tell me version of https://github.com/codex-team/editor.js.
