### ISSUE TITLE
Pass Props From Editor.js to Custom Block

### ISSUE THREAD

**Issue by PurplePineapple123** [Jungwoo-An/react-editor-js#144]
How do props get passed from the Editor.js component to a custom created block? 

I have an editor.js component and also created a custom checklist block. I'm trying to pass props containing the url params ```props.match.params.id```.  However, I'm unable to pass props through editor.js to the custom child block normally ( ```props={props}```). 

Any idea how to make this work? Thanks!

**Comment by Jungwoo-An** [comment]
@PurplePineapple123 Hi! First of all, thanks for your interest! 👋 

I think you should create custom tools for custom block.

Thanks!
