### ISSUE TITLE
"element with ID «...» is missing. Pass correct holder's ID."

### ISSUE THREAD

**Issue by SFromentarius** [Jungwoo-An/react-editor-js#151]
### Environment

- @editorjs/editorjs version: 2.22.2
- react-editor-js version: 1.10.0

### Describe

Not preventing from use, but there is some errors in the console
<img width="257" alt="Capture d’écran 2021-10-04 à 18 43 29" src="https://user-images.githubusercontent.com/30386836/135890977-c5dca33b-0353-4212-9196-203b57fc4f5f.png">

**Comment by batiyeh** [comment]
@Jungwoo-An @SFromentarius I have also been facing this issue and its been using up my Sentry quotas. This resolved the problem for me: https://github.com/batiyeh/react-editor-js/commit/71e96c191bcc1578aa9f57145cf154f6e8abd776

**Comment by batiyeh** [comment]
@Jungwoo-An no, only the above minor change was required.

**Comment by Jungwoo-An** [comment]
@batiyeh Did you use nextjs? (or other ssr framework) If you are using ssr, you must set the holder.

**Comment by batiyeh** [comment]
Nope - just a normal SPA from create-react-app
