### ISSUE TITLE
enableReInitialize prop is still not working

### ISSUE THREAD

**Issue by RathanakSreang** [Jungwoo-An/react-editor-js#16]
I saw we already have PR for that. However, this issue still happened.

**Comment by Jungwoo-An** [comment]
@RathanakSreang Hi! First of all, thanks for your interest! ❤️ 

Can you serve me reproduce link? (ex: [codesandbox](https://codesandbox.io/))

Thanks!

**Comment by kbarnesweb** [comment]
I am having an issue with enableReInitialize prop.  I set data to {this.state.blogBody}. 
blogBody is initially null as it is awaiting fetch from redux action.  The data attribute doesn't work unless I have enableReInitialize prop set to true.

When I set enableReInitialize prop to true, two editors appear with the same blog body in each one.

**Comment by bilalbutt044** [comment]
after  adding `enableReInitialize` how to add `onchange` functioanlity ? i want to get data on Change.
I guess i am implementing in wrong way. here is my sandbox @Jungwoo-An  
https://codesandbox.io/s/react-editor-js-h70bb

**Comment by Doamax** [comment]
I'm having a similar problem as kbarnesweb where I see two editors at times, and both only show the loading circle animation. I've successfully initialized with data from the useState hook, but when I use enableReinitialize in order to change the data, I have the problem described above.

**Comment by Jungwoo-An** [comment]
I'm sorry for late reply. I will check this issue asap. Thanks!

**Comment by Doamax** [comment]
I was able to fix my problem like this:
`    const [editorInstance, setEditorInstance] = useState(null);
    useEffect(()=>{
        if(display && editorInstance){
            if(conditions){
                editorInstance.clear();
            }else{
                editorInstance.render(props.data);
            }
        }
    },[props.thatShouldForceUpdates])

//within component
                    <EditorJs
                        data={props.data}
                        instanceRef={instance => setEditorInstance(instance)}
                        tools={{
                            ...COURSE_TOOLS
                        }}
                    />
`

**Comment by Jungwoo-An** [comment]
Hi! I made new PR (#26). I think this issue will be solved after merge PR #26 

PR will be merged into master branch by tomorrow at the latest. If anyone have opinion, please PR comment

Thanks!

**Comment by Jungwoo-An** [comment]
#26 PR has been merged. So i'll close this issue. If anyone have anything to say, please open issue.

**Comment by Jungwoo-An** [comment]
> after adding `enableReInitialize` how to add `onchange` functioanlity ? i want to get data on Change.
> I guess i am implementing in wrong way. here is my sandbox @Jungwoo-An
> [codesandbox.io/s/react-editor-js-h70bb](https://codesandbox.io/s/react-editor-js-h70bb)

You can get changed data after define onChange prop. ([Example](https://codesandbox.io/s/react-editor-js-0lf0u))

Thanks!
