### ISSUE TITLE
Not able to use Embed and Code plugins

### ISSUE THREAD

**Issue by mkholjuraev** [Jungwoo-An/react-editor-js#169]
### Environment

- @editorjs/editorjs version: 2.22.2
- react-editor-js version: 2.0.3

### Describe

First of all, thanks for the great app!

I have some bugs and need help to resolve them:

I am not able to use the Code plugin. I can successfully install it, users can type some code. But after a few chars entered, code editor throws: t.some is not a function.

Also, Embed plugin is not visible in the UI at all.

**Comment by Jungwoo-An** [comment]
@mkholjuraev Hi! First of all, thanks for your interest! 👋 

It looks like a bug of editor-js. https://github.com/codex-team/editor.js/issues/1750

Thanks!
