### ISSUE TITLE
Difficulty with loading defaultValue blocks

### ISSUE THREAD

**Issue by gonsaje** [Jungwoo-An/react-editor-js#170]
### Environment

- @editorjs/editorjs version: ^2.22.2
- react-editor-js version: ^2.0.3

### Describe

I am trying to implement react-editor with pre-existing document templates. It seems that when I try to use the defaultValue prop in the ReactEditorJS component, nothing is displayed.

Code:

`
```
const dummyTemplate = [
  {
    data: { level: 2, text: 'Company Name:' },
    type: 'header',
  },
  { data: { level: 4, text: 'Date:' }, type: 'header' },
];

const ReactEditorJS = createReactEditorJS();
const editorJS = useRef(null);
const handleInitialize = useCallback((instance) => {
    editorJS.current = instance;
}, []);


// return

 <ReactEditorJS
        defaultValue={temp}
        onInitialize={handleInitialize}
        tools={EDITOR_JS_TOOLS}
/>
```
`

I think I'm a little confused as to how the defaultValue should be configured.

Thanks in advance, Jungwoo!

**Comment by gonsaje** [comment]
I found out that we need to pass the entire editor object instead of just the blocks array. Thank you anyways

**Comment by robertseghedi** [comment]
How did you solve this? It's still unclear for me

**Comment by robertseghedi** [comment]
Nevermind, sorry for the reply.

For anyone having the same problem, take a look in here: https://codesandbox.io/s/react-editor-js-v2-34bfl?file=/src/index.js:365-5051 to understand the way the property is built. You have to pass the entire object. I was saving in my database only the blocks.
