### ISSUE TITLE
test coverage & types

### ISSUE THREAD

**Issue by AdrienLemaire** [Jungwoo-An/react-editor-js#171]
Hi there,

We'd like to use your library to integrate editor-js in our react app (thanks for making it), and I was wondering about the code coverage.
I understand that editor.js has some good coverage for its code, but it'd be reassuring to confirm that the wrapper also does what it is supposed to do and doesn't accidentally break in a future release.
Would you be able to add some tests in your package ?

On another note, it seems like the types for this package aren't exported, and we cannot use them in our repo. Could you look into it ?

Thanks for your support :bow:

**Comment by Jungwoo-An** [comment]
@AdrienLemaire Hi! First of all, thanks for your interest! 👋 

I'm sorry for the late response. I'm busy a little. I think I missed the typing file during the v2 release. I'll upload it.

Thanks!

**Comment by Jungwoo-An** [comment]
I added typing file and published! (v2.0.4)

**Comment by Jungwoo-An** [comment]
react-editor-js achieved sustainability through unit testing https://github.com/Jungwoo-An/react-editor-js/blob/master/packages/%40react-editor-js/core/tests/ReactEditorJS.spec.tsx

Thank you for the good suggestion!

**Comment by AdrienLemaire** [comment]
@Jungwoo-An I tried to upgrade the package to v2.0.5 (cannot upgrade to v2.0.6 because of #183), and it seems like the types cannot be imported from my project.
It looks like types are defined in the directory `@react-editor-js`, and maybe they aren't being exported when bundling the npm package ?

**Comment by Jungwoo-An** [comment]
@AdrienLemaire Why can't upgrade to latest version? Can you show me use-case? plz 🙏🏻
