### ISSUE TITLE
Unable to access state (or any other component variable) inside uploadByFile

### ISSUE THREAD

**Issue by aiavci** [Jungwoo-An/react-editor-js#174]
### Environment
- @editorjs/editorjs version: 2.22.2
- react-editor-js version: 2.0.3

### Describe
State parameters are always undefined in uploadByFile

### Sample code
```
<ReactEditorJS
  onChange={(e: any) => handleChange(e)}
  instanceRef={(instance: any) => {
    return (instanceRef.current = instance);
  }}
  tools={{
    image: {
      class: Image,
      config: {
        uploader: {
          uploadByFile: (f) => {
            // Unable to get state here!
          },
        },
      },
    },
  }}
/>;
```

**Comment by Jungwoo-An** [comment]
@aiavci Hi! First of all, thanks for your interest! 👋 

Could you provide me reproduce link? (Github, Codesandbox, ...)

Thanks!

**Comment by aiavci** [comment]
https://codesandbox.io/s/interesting-allen-x42xk

**Comment by Jungwoo-An** [comment]
@aiavci By default, react-editor-js is uncontrolled component. Therefore, tool initialization only once when mounting for the first time.

If you want workaround, feel free to pull request!

Thanks!
