### ISSUE TITLE
ReferenceError: blocks is not defined

### ISSUE THREAD

**Issue by zacharykatsnelson** [Jungwoo-An/react-editor-js#179]
### Environment

- @editorjs/editorjs version: "^2.22.2"
- react-editor-js version: "^2.0.6"

### Describe

Hello, 
I have tried to start by running the exact code as specified in the readme. My component simply is this:

```
import React from 'react';
import { createReactEditorJS } from 'react-editor-js';

const ReactEditorJS = createReactEditorJS();

function Write() {
  return (
    <div>
      <h1>Testing</h1>
      <ReactEditorJS defaultValue={blocks} />
    </div>
  );
}

export default Write;
```
Yet I am getting this error:
`Cannot find name 'blocks'`

I have no idea what is going wrong. I literally haven't even gone through the first example yet and already am stuck on something. -.-

**Comment by zacharykatsnelson** [comment]
+ another note that could be of interest... If I remove defaultvalue={blocks} I get this error:

```
Unhandled Runtime Error
Error: element with ID «react-editor-js-17e0f3a8dcd» is missing. Pass correct holder's ID.

```

**Comment by Jungwoo-An** [comment]
@zacharykatsnelson Hi! First of all, thanks for your interest! 👋 

When using SSR (nextjs, ...), Holder prop must be set explicitly.

```ts
<ReactEditorJS holder="ssrHolder" />
```

Thanks!
