### ISSUE TITLE
Can't find an option to change the fonts.

### ISSUE THREAD

**Issue by xNicklaj** [Jungwoo-An/react-editor-js#18]
Probably I'm just missing it, but I really can't find that option. Could you tell me how to do it?

**Comment by Jungwoo-An** [comment]
@xNicklaj Hi! First of all, thanks for your interest! ❤️

By default, editor-js inherit font-family of parent element.
If you want to change the font-family, you should set it as below code

```tsx
render() {
  return (
    <div class="wrapper" style={{ fontFamily: '' }}>
      <EditorJs />
    </div>
  );
}
```

Thanks!

**Comment by Jungwoo-An** [comment]
I closed this issue. If you have anything more to say, plz reopen issue.

Thanks!
