### ISSUE TITLE
Inject block programmatically?

### ISSUE THREAD

**Issue by orbachar** [Jungwoo-An/react-editor-js#180]
Hi I wonder if is there a way to inject a new block to editor js, programmatically, from an outside event, while allowing to edit the content with the regular behavior of onChange prop.

the way I though of doing that, was to listen to onChange prop as usual, get the blocks on save, and when an outside event happens, push a new block to the content returned from `onChange`, and pass it on `value` prop.
Unfortunately using both `value` and `onChange` props cause infinite loop.

I wonder if is there another way achieving that?

**Comment by Jungwoo-An** [comment]
@orbachar Hi! First of all, thanks for your interest! 👋 

Can you show me an example of the use case?

Thanks!

**Comment by orbachar** [comment]
eventually I managed to make it work by using the editor core instance and use it's render function to update the editor content externally 

![image](https://user-images.githubusercontent.com/57751360/151762200-f3351871-c84d-49dc-a3b4-1a120ac32c43.png)
