### ISSUE TITLE
Read Only

### ISSUE THREAD

**Issue by Ashish-3000** [Jungwoo-An/react-editor-js#186]
Can you add read-only feature I have tried to access it from the instance created but the object fields are added after some time so that's why it's hard to access it.

**Comment by Jungwoo-An** [comment]
@Ashish-3000 Hi! First of all, thanks for your interest! 👋 

You can use readOnly Prop 🙌🏻 

Thanks!

**Comment by Jungwoo-An** [comment]
@Kentakoong Oh, Thank you! I'll fix it.
