### ISSUE TITLE
Is there a way to lock the content?

### ISSUE THREAD

**Issue by vincecao** [Jungwoo-An/react-editor-js#19]
Hi, I want to prevent alter the content in some condition, is there a way to lock the content preventing text content changing? Thanks.

**Comment by Jungwoo-An** [comment]
@vincecao Hi! First of all, thanks for your interest! ❤️

Do you want readonly mode? If so editor-js is not support readonly mode. Therefore, data blocks in the web environment need to be converted to html code. looks like [this](https://repl.it/@GodwinOnimisi/heloo) ([Ref](https://github.com/codex-team/editor.js/issues/676))

Thanks!

**Comment by Jungwoo-An** [comment]
I closed this issue. If you have anything more to say, plz reopen issue.

Thanks!

**Comment by JoyTerence** [comment]
@Jungwoo-An, looks like from 2.19 editor.js supports [readonly mode](https://github.com/codex-team/editor.js/issues/837).

**Comment by Jungwoo-An** [comment]
@JoyTerence Wow! 👍

**Comment by davibarreira** [comment]
I'm trying to use the "readOnly" option, but it's not working. Is the feature not implemented with the React editor yet?

**Comment by JoyTerence** [comment]
@davibarreira , not yet, I added this minor [change ](https://github.com/JoyTerence/react-editor-js/commit/6fd1d9f3b2fe6686e7b6dc80631de534d3ad8c87) and built it to make use of the readonly feature.

**Comment by Ashish-3000** [comment]
How can we pass it react-editor-js to use it as read-only??
