### ISSUE TITLE
Set editor to only reading mode

### ISSUE THREAD

**Issue by ammasum** [Jungwoo-An/react-editor-js#197]
I want to make editor only reading mode. How can I achieve this?

**Comment by StitiFatah** [comment]
```   
editorCore.current.readOnly.toggle()
```
it's working one 2.0.3 on my end but 2.0.6 throw `TypeError: Cannot read properties of undefined (reading 'toggle')` tho

**Comment by Jungwoo-An** [comment]
@ammasum Hi! First of all, thanks for your interest! 👋 

You can use readOnly prop

Thanks!
