### ISSUE TITLE
Editor doesn't work when passing the tools prop

### ISSUE THREAD

**Issue by itzmukeshy7** [Jungwoo-An/react-editor-js#2]
When passing the tools prop, the editor doesn't work.

`<EditorJs tools={toolsObject} />`

**Comment by Jungwoo-An** [comment]
Thanks for you are interest! 😍 

this issue is not error. it's my intention. but i know should change api..
i will update version (current version is 1.3.0) to 1.3.1. you can use the following code.

```ts
// this is will extend default tools of editor.js
<EditorJs tools={{ customToool: customTool }} />
````

**Comment by Jungwoo-An** [comment]
You can use the code above now!!

**Comment by itzmukeshy7** [comment]
Great, can you please update the [@editorjs/editorjs](https://github.com/Jungwoo-An/react-editor-js/blob/master/package.json#L34) to the latest version as well?

And it's awesome!

**Comment by Jungwoo-An** [comment]
It is already supported. just update your package.

**Comment by itzmukeshy7** [comment]
Perfect, thank a lot!
