### ISSUE TITLE
A way to edit the initial loading spinner

### ISSUE THREAD

**Issue by pisacode** [Jungwoo-An/react-editor-js#201]
When the editor initialize there is a spinner very briefly visible. This causes content to grow and shrink when the loading state changes. 

If we can added a custom loading component and edit the styles of the loading component it would look more elegant. 

I tried to catch the loading indicator to see the css props but it is very fast for me to catch it in the inspector.

Thanks for the amazing package.

**Comment by Jungwoo-An** [comment]
@pisacode Hi! First of all, thanks for your interest! 👋 

Yes you can. Check out [this page](https://editorjs.io/styles)

Thanks!
