### ISSUE TITLE
Can't Input Text

### ISSUE THREAD

**Issue by taufik-nurhidayat** [Jungwoo-An/react-editor-js#206]
### Environment

- "@editorjs/editorjs": "^2.25.0",
- "@editorjs/header": "^2.6.2",
- "@editorjs/paragraph": "^2.8.0",
- react-editor-js version:  "^2.1.0"

### Describe

I can't Input anything, but no warning or error in console. 
This is my code
```js 
// pages/newpost.js
import dynamic from 'next/dynamic'
const CustomEditor = dynamic(()=>import('../components/editor'),{ssr:false})
export default function NewPost(){
  return (
    <> <CustomEditor /></>
  )
}
```
Components code
```js 
// components/editor.js
import { createReactEditorJS } from 'react-editor-js'                                   
const Header = require('@editorjs/header')
export default function CustomEditor({data}){

  const ReactEditorJS = createReactEditorJS()

  const TOOLS = {
    header: Header,
  }
 return(
    <ReactEditorJS tools={TOOLS} holder="editor">                                 
<div id="editor" className="my-4 border h-64 relative"></div>
    </ReactEditorJS>
  )
}
```

In console that is ready to use but, I try tap the editorjs and not do anything
![IMG_20220721_115353](https://user-images.githubusercontent.com/48739090/180132708-46144bb5-2a23-4cd4-8603-b1b4d18192a2.jpg)

**Comment by taufik-nurhidayat** [comment]
![IMG_20220721_130033](https://user-images.githubusercontent.com/48739090/180140492-194925cf-d85a-436f-9f30-0a9b92eaff46.jpg)

after look element is like EditorJS not rendered

**Comment by Maxfri** [comment]
Perhaps you should disable <React.StrictMode> in your index.jsx

**Comment by msnisha** [comment]
@Maxfri  Thanks it helped me to solve rending issue. Is it a bug needs to be addressed in the component to support strict mode?
