### ISSUE TITLE
Where is the file data during request to server?

### ISSUE THREAD

**Issue by avillarubia** [Jungwoo-An/react-editor-js#21]
Good day guys,

I have a summary of my concern below

```
const EDITOR_JS_TOOLS = {
    image: {
        class: Image,
        config: {
            endpoints: {
                byFile: 'http://localhost:3001/api/uploads'
            },
            field: 'image',
            types: 'image/*'
        }
    }
}

const CommentEditor = () => {
    return <EditorJs tools={EDITOR_JS_TOOLS} />
}
```
When my react sends request to

```
router.post('/', async (req, res) => {
//when client use this endpoint, console.log can display a message
})
```
but where is the data?
I look it to req.body but empty

Thank you.

**Comment by Jungwoo-An** [comment]
@avillarubia Hi! First of all, thanks for your interest! ❤️

I think you want to change request of upload img. is right? If so, you should follow this [section](https://github.com/editor-js/image#providing-custom-uploading-methods)

Thanks!

**Comment by avillarubia** [comment]
@Jungwoo-An thanks for the response, As I checked, I found out that there is no file upload support other than image (correct me if I am wrong). Do you have plans to implement that idea?

**Comment by Jungwoo-An** [comment]
@avillarubia Are you talking about static file upload? If so, I don't have plans. 😥 

Thanks!

**Comment by avillarubia** [comment]
Yes @Jungwoo-An

**Comment by sabit990928** [comment]
> @avillarubia Are you talking about static file upload? If so, I don't have plans. 
> 
> Thanks!

Is it mean that byFile functionality from "image" library don't work?
