### ISSUE TITLE
 I don't know how to bring articles edited from this library to users

### ISSUE THREAD

**Issue by phongw** [Jungwoo-An/react-editor-js#22]
Hi,
This is a very good library, I want to use this library to make a personal blog site, but I don't know how to bring articles edited from this library to users, I just want to give users View the content of the article and not edit it.
help me. thanks.

**Comment by Jungwoo-An** [comment]
@phongw Hi! First of all, thanks for your interest! ❤️

It seems to me that you want read-only mode. But, editor-js has only support write-only mode. Therefore, data blocks need to be converted to html code. looks like [this](https://repl.it/@GodwinOnimisi/heloo) ([Ref](https://github.com/codex-team/editor.js/issues/676))

(I have plan to support read-only mode in react-editor-js library)

Thanks!

**Comment by phongw** [comment]
Thank you.
