### ISSUE TITLE
Not able to change css of react editor

### ISSUE THREAD

**Issue by danilockthar** [Jungwoo-An/react-editor-js#27]
Im not getting how to change the style of react editor . In the editor docs page they use classes in the divs but with react editor we only have a <ReactEditor > component. What is the best way to change the style of the component ?

**Comment by Jungwoo-An** [comment]
@danilockthar Hi! First of all, thanks for your interest! ❤️

You must override default class of editor.js. ([Docs](https://editorjs.io/styles))

Thanks!

**Comment by Jungwoo-An** [comment]
I close this issue. If you have anything more to say, plz reopen issue.

Thanks!
