### ISSUE TITLE
Can't save state of EditorJS

### ISSUE THREAD

**Issue by pitis** [Jungwoo-An/react-editor-js#28]
I'm using React 16.13.1 and I can't seem to find a way to save the state.
I tried using useEffect for initialization but it didn't work. We need an update where there is a easy way to save the data with hooks.

**Comment by Jungwoo-An** [comment]
@pitis  Hi! First of all, thanks for your interest! ❤️

Do you want [this example](https://codesandbox.io/s/react-editor-js-o2n3b)?

**Comment by pitis** [comment]
Yes, this works. Thank you very much. Could you put that link in the documentation as well? I saw other people on StackOverflow that were trying the same thing but couldn't do it.

Thanks again for the fast response.

**Comment by Jungwoo-An** [comment]
@pitis I'm glad i helped you. I'll add example link to documentation.

Thanks.

**Comment by Darren120** [comment]
can u add some types, nextjs complaining but code compiles fine.
