### ISSUE TITLE
Listening to events

### ISSUE THREAD

**Issue by moringaman** [Jungwoo-An/react-editor-js#29]
Please could you provide an example of how to listen to changes in blocks via useEffect or any other method as I am having issues working out how to do this. Thanks

**Comment by Jungwoo-An** [comment]
@moringaman Hi! First of all, thanks for your interest! ❤️

Do you want [this example](https://codesandbox.io/s/react-editor-js-0lf0u)? Thanks

**Comment by Jungwoo-An** [comment]
I close this issue. If you have anything more to say, plz reopen issue.

Thanks!

**Comment by moringaman** [comment]
Apologies for not acknowledging your response, I was a bit bogged down at the time, the example you provided was perfect. 
Thankyou!
