### ISSUE TITLE
Read Only mode for react editor js 

### ISSUE THREAD

**Issue by paritosh9199** [Jungwoo-An/react-editor-js#30]
Is there a way to preview the entire content without being able to edit it (preventing user from editing).

**Comment by Jungwoo-An** [comment]
@paritosh9199 Hi! First of all, thanks for your interest! ❤️

This issue is duplicated. plz [check here](https://github.com/Jungwoo-An/react-editor-js/issues/19#issuecomment-575421490)

Thanks!

**Comment by Jungwoo-An** [comment]
I close this issue. If you have anything more to say, plz reopen issue.

Thanks!
