### ISSUE TITLE
Demo Different in browser and sandbox. 

### ISSUE THREAD

**Issue by Ritace** [Jungwoo-An/react-editor-js#32]
![image](https://user-images.githubusercontent.com/6260237/80204104-fafe6f00-8647-11ea-9ae8-3f9a8a030f11.png)

When I saw demo of react-editor-js in browser I saw the above image. It can clearly be seen that the section in which user clicks is highlighted and + icon is shown which allows addition of blocks. 

But when I run the same demo in my browser then I when I click on any component the component is not highlighted and plus icon not showing. I am confused. Below you can see the image of when I click component in my browser.
![image](https://user-images.githubusercontent.com/6260237/80204506-b7f0cb80-8648-11ea-9412-7ee6bd7634c8.png)

Am I missing something? 

I tried upgrading node. I am using javascript and not typescript.

**Comment by Jungwoo-An** [comment]
@Ritace Hi! First of all, thanks for your interest! ❤️

Can you provide reproduce code me? (ex: CodeSandbox)

Thanks.
