### ISSUE TITLE
Cannot read property 'querySelector' of null on checklist item blur

### ISSUE THREAD

**Issue by salatielq** [Jungwoo-An/react-editor-js#34]
I'm getting this error when tried the example code. 

https://media.giphy.com/media/Y0tRCzeOyF7U2kwMYn/giphy.gif

**Comment by Jungwoo-An** [comment]
@salatielq Hi! First of all, thanks for your interest! 👋 

I've same experience as screenshot. It's exactly checklist issue. If you don't mind, can you make new issue to [checklist repo](https://github.com/editor-js/checklist/issues)?
