### ISSUE TITLE
Update  Content Dynamically

### ISSUE THREAD

**Issue by octalpixel** [Jungwoo-An/react-editor-js#35]
I run into an infinite look when i hook into the onChange function and update the content using  .blocks.render(). This behaviour is understandable,but is  there anyway to update the content ?

**Comment by Jungwoo-An** [comment]
@octalpixel Hi! First of all, thanks for your interest! 👋 

Try the using [enableReInitialize](https://github.com/Jungwoo-An/react-editor-js#-api) prop. I think it will help you.

Thanks
