### ISSUE TITLE
Multiple CSS style applied

### ISSUE THREAD

**Issue by NuriddinK** [Jungwoo-An/react-editor-js#38]
Hello, CSS is repeated for each blocks. Is there a way to unify styling?

![image](https://user-images.githubusercontent.com/16413679/82076627-6df68500-96de-11ea-9731-daf82e8dea7b.png)

**Comment by Jungwoo-An** [comment]
@NuriddinK Hi! First of all, thanks for your interest! 👋 

This library does not create styles. Please create an issue in [editor-js repository](https://github.com/codex-team/editor.js)

Thanks!
