### ISSUE TITLE
How can I set a placeholder?

### ISSUE THREAD

**Issue by MohitKS5** [Jungwoo-An/react-editor-js#39]
I tried setting on instance but it didn't work. I tried passing as prop still no luck.  Passing to instance and setting enableReInitialize to true also didnt work.

**Comment by Jungwoo-An** [comment]
@MohitKS5 Hi! First of all, thanks for your interest! 👋 

You can set placeholder! please read [this issue](https://github.com/codex-team/editor.js/issues/606)

Thanks!

**Comment by MohitKS5** [comment]
Thanks.
