### ISSUE TITLE
[request] new prop `exclude`

### ISSUE THREAD

**Issue by VLZH** [Jungwoo-An/react-editor-js#4]
@Jungwoo-An Hello! What do you think about new prop `exclude`? For excluding of default tools, because I cant to overwrite some tool to `undefined`

**Comment by Jungwoo-An** [comment]
@VLZH Thanks to your interest! 😍 

i have been think about your proposal, and i like it. i will update soon. 👍

**Comment by Jungwoo-An** [comment]
@marianrick Hi! thanks to your interest 😍

for the reason above, i agreed. feel free to pull request.

**Comment by marianrick** [comment]
Sorry for my late response, I have missed the notification. I have created a pull request, removed the default tools and added only Paragraph again.

Although I have added a hint about this to the README file and a short tutorial how users can add their tools back again 🙂

https://github.com/Jungwoo-An/react-editor-js/pull/7
