### ISSUE TITLE
Content data is not updating after rerendering 

### ISSUE THREAD

**Issue by Ritace** [Jungwoo-An/react-editor-js#40]
Hello There. I am building a text editor where user can save the content. I have successfully saved the contet in a server. But when I retireve it and update the state. Editor is successfully rerendering but the data change is not displayed. 
 ```
getDataCallBack(res){
      //set set if data is not empty
      if( ! (res.data['emailJson'] === {}) ){
        // console.log(res.data['emailJson']);
        this.kidding = "Data is loaded";
        this.setState({
          data: {blocks:res.data['emailJson']}
        });
    
      }
    }
```
This is the call back function i use after the data has been fetched. 
```
 componentDidMount() {
        getEmail(this.getDataCallBack);
}
```
This is the data fetching function 

```
 render() {
      return (
          <div>
            <EditorJs
              instanceRef={instance => this.editorInstance = instance}
              tools={EDITOR_JS_TOOLS}
              data={this.state.data}
            />
            <Button style={{'background': 'blue', 'textAlign': 'center'}}  onClick={this.handleSave}>Save</Button>
        </div>
      );
    }
```

I am quite sure the rerender is happening because when i print value inside render to see the data. I can clearly see the data is updated and not the old value. 
I don't know why in the rerender even though this.state.data is updated the content is not updated.

**Comment by Ritace** [comment]
Sorry there just found the solution. 
Add enableReInitialize = {true}. 
Your editorjs would look like
<EditorJs
             enableReInitialize={true}
              tools={EDITOR_JS_TOOLS}
              data={this.state.data}
            />

**Comment by akhil-gautam** [comment]
I am facing a related issue. After `enableReInitialize={true}`, it is rendering every block twice. 
![Screenshot 2021-08-02 at 12 09 34 PM](https://user-images.githubusercontent.com/28865023/127815402-a30cc98e-d1b5-42ec-bbf3-2e7837804d2f.png)

**Comment by akhil-gautam** [comment]
@Jungwoo-An Please let me know what would be going wrong? Is it that I have to explicitly compare the blocks?
