### ISSUE TITLE
It is possible to activate 'convert to' option in the inline block editor?

### ISSUE THREAD

**Issue by f-naranjo** [Jungwoo-An/react-editor-js#41]
Hi! Im wondering if there is the possibility to activate the option to change block type once you have selected one.

For example, when you start writing and you select the text, the editor let you choose to change between Header and Paragraph, but once you select one of the options, this options doesn't appear anymore.

Hope these  images can help to explain the question:

1. When i write the text without selecting Header or Paragraph and mouseover:
![Captura de pantalla 2020-05-25 a las 10 54 56](https://user-images.githubusercontent.com/4303992/82796701-46d64b00-9e76-11ea-8426-83243a1020ce.png)

2. Once I select "Header" or "Paragraph", the `convert to` tool doesn't appear anymore:
![Captura de pantalla 2020-05-25 a las 10 55 05](https://user-images.githubusercontent.com/4303992/82796719-4f2e8600-9e76-11ea-8598-d4585b6a9229.png)

Thanks for the good work!

**Comment by Jungwoo-An** [comment]
@f-naranjo  Hi! First of all, thanks for your interest! 👋 

It's impossible feature. If you want new feature, create new issue in [editor-js repo](https://github.com/codex-team/editor.js).

Thanks!

**Comment by f-naranjo** [comment]
Hi again!

Here I add a gif of the editor-js example where i can do this tranformation, so i think editor-js already has this feature:

![ezgif-4-8cebf241ff31](https://user-images.githubusercontent.com/4303992/82902759-3dc1a880-9f60-11ea-8d58-f69c33cc64c9.gif)

Maybe there is a way to do this in react-editor-js ?

Thanks again for your rapid answer!

**Comment by Jungwoo-An** [comment]
@f-naranjo 

I'm sorry. It's my mistake. 😥 

It's new feature of v2.16.0. You just have to update editor-js. (`yarn upgrade @editorjs/editorjs` or npm)

Thanks! 👍

**Comment by tailor-hub-mad** [comment]
Omg, it is so easy to enable it, sorry for all the questions! If anyone has the same issue it's necessary to update `editor-js` and enable de `inlineToolbar` like this:

```javascript
      tools.paragraph = {
		class: Paragraph,
		inlineToolbar: true,
		};
```

As a recommendation, maybe you can update de example in de sandbox to see this inline editor working perfectly ;) (I did it and it worked perfect)

Thanks for your time! Hope this question can help someone

Cheers!🍻

**Comment by f-naranjo** [comment]
Omg, it is so easy to enable it, sorry for all the questions! If anyone has the same issue it's necessary to update `editor-js` and enable de `inlineToolbar` like this:

```javascript
      tools.paragraph = {
		class: Paragraph,
		inlineToolbar: true,
		};
```

As a recommendation, maybe you can update de example in de sandbox to see this inline editor working perfectly ;) (I did it and it worked perfect)

Thanks for your time! Hope this question can help someone

Cheers!🍻
