### ISSUE TITLE
Infinite update on onChange

### ISSUE THREAD

**Issue by yul761** [Jungwoo-An/react-editor-js#42]
Hi, 

I set enableReInitialize to true and in the onChange Method, I call the save method. It works fine at first, but as soon as I insert new data to 'data' props, it seems like the 'onChange' is triggered infinitely. Any way to break this loop?

`<EditorJs
        instanceRef={(instance) => (editorInstance = instance)}
        onChange={() => handleSave(editorInstance)}
        data={editorData}
        enableReInitialize={true}
        tools={EDITOR_JS_TOOLS}
      />`

`const handleSave = async (instance) => {
    const savedData = await instance.save();
    setData(savedData);
  };`

The editorData is set to empty string at first, and later it has chances to update to new data when clicking one button,  which means that I want the onChange only triggered when typing something in the editor field, and when the value of editorData is updated, the text in the editor is updated. Currently, whenever the editorData is updated, onChange is triggered like forever.

It would be so appreciated if you could offered any help.

Thanks.

Follow up:
 
I did a little bit debugging. 
<img width="501" alt="Screen Shot 2020-05-31 at 11 09 38 PM" src="https://user-images.githubusercontent.com/15523223/83377891-410bc880-a394-11ea-881b-c759fea4c6b0.png">

I am not quite sure but I think it may be caused by timestamp changes.
The text in blocks[0].data.text is not changing, but as the timestamp keeps updating, the onChange is keep triggering. I am not sure if this is the issue, but if it is, is there any way to custom config onChange?

**Comment by Stiivenson** [comment]
Hi, @yul761 .
I've faced the same issue while building notes-writing-system. Use Redux to load data and bump into infinite loop after loading data from _onChange() function_.  If I set **enableReInitialize** to false - Editor won't load data from Server =/
Not sure, that my solution is correct, but it helped to get rid of infinite trap.
I just put another item in State (**enableReInitialize: true**) and provide it in render. 
```jsx
<EditorJs 
instanceRef={instance => this.editorInstance.current = instance}
onChange={this.handleSave}
enableReInitialize={this.state.enableReInitialize}
 />  
```

Data loaded and I disable **enableReInitialize** in _handleSave():_
```jsx
handleSave = () => {
if(this.state.enableReInitialize) this.setState({ enableReInitialize: false });
...
```

If I need to load new data, I use _getDerivedStateFromProps()_ and set  **enableReInitialize** true again:
```jsx
static getDerivedStateFromProps(props, state) {
    if(state.id !== props.document.id) {
      ...
      return {
        id: props.document.id,
        title: props.document.title,
        data: {
          blocks: props.document.docBody
        },
        enableReInitialize: true
      }
    } 
    return null;
}
```
Hope this'll help you

**Comment by mqtik** [comment]
That's not a viable choice for production use, too hacky.

**Comment by Jungwoo-An** [comment]
@yul761 Hi! First of all, thanks for your interest! 👋 

By default, react-editor-js is uncontrolled component. Therefore, using enableReInitialize with onChange is not a good way. But I think unpredictable behavior is problem. I'll solve this issue asap.


Thanks!

**Comment by mqtik** [comment]
I'll stay tuned for updates!

**Comment by Jungwoo-An** [comment]
@yul761 (@mqtik) Hi! I'm released v1.6.0. You can avoid infinite loop using onCompareBlocks prop. ([Docs](https://github.com/Jungwoo-An/react-editor-js#-api))

Example code below

```jsx
<EditorJs
  data={data}
  onChange={handleChange}
  onCompareBlocks={(newData, oldData) => newData === oldData} // I recommend react-fast-compare
  enableReInitialize
/>
```

Thanks!

**Comment by Jungwoo-An** [comment]
I close this issue. If you have anything else to say, please reopen issue.

**Comment by danilockthar** [comment]
> @yul761 (@mqtik) Hi! I'm released v1.6.0. You can avoid infinite loop using onCompareBlocks prop. ([Docs](https://github.com/Jungwoo-An/react-editor-js#-api))
> 
> Example code below
> 
> ```js
> <EditorJs
>   data={data}
>   onChange={handleChange}
>   onCompareBlocks={(newData, oldData) => newData === oldData} // I recommend react-fast-compare
>   enableReInitialize
> />
> ```
> 
> Thanks!

Hi, im getting an infinite loop but this doesnt stop it. What i im missing ? this is my code:

```
  function handleChange(_api, newData) {
    setContenido(newData);
  }
--
<EditorJs
          tools={EDITOR_JS_TOOLS}
          instanceRef={(instance) => (editorRef.current = instance)}
          data={contenido}
          onChange={handleChange}
          onCompareBlocks={(newData, oldData) =>
            setenableChange(newData === oldData ? false : true)
          }
          enableReInitialize={enableChange}
        />
```

**Comment by Jungwoo-An** [comment]
@danilockthar Hi, is setenableChange return type boolean?

**Comment by moxxuk** [comment]
Can we have a clear example of how this should be implemented? I'm trying a lot of different configurations, but I just can't get it to work.
