### ISSUE TITLE
package.json: `module` doesn't exist

### ISSUE THREAD

**Issue by stephtr** [Jungwoo-An/react-editor-js#45]
The file mentioned in package.json's `module` property (`./dist/react-editor-js.js`) doesn't exist in the final bundle. I guess there's a `.es` missing in the filename?

**Comment by Jungwoo-An** [comment]
@stephtr Hi! First of all, thanks for your interest! 👋 

Oh, It's my mistake. I'll add .es to file extension

Thanks!

**Comment by Jungwoo-An** [comment]
#46 merged. I'll close this issue. If you have anything else to say, please reopen issue

**Comment by stephtr** [comment]
Thank you for your work!
