### ISSUE TITLE
I am not able to store the data

### ISSUE THREAD

**Issue by neeth-kun** [Jungwoo-An/react-editor-js#47]
I need to access the data when Save Button is pressed, but all the methods I tried to use are failing.
Cannot set property 'editorInstance' of undefined is the error I am getting when I try to access the Instance of EditorJS.
Can anyone who has done this, send their syntax and working?

**Comment by neeth-kun** [comment]
This query has already been resolved. Thank You

**Comment by neeth-kun** [comment]
I would like to log this data into a console or a database. But I am not able to access the data attribute in the first place. When I create an instance in the EditorJs tag, it shows Undefined. How do I overcome this?

**Comment by Ajitesh13** [comment]
I am also facing the same problem. How to access the returned data from the editor ?

**Comment by Jungwoo-An** [comment]
@neeth-kun Hi! First of all, thanks for your interest! 👋 

Can you provide reproduce code to me? (ex: CodeSandbox)

Thanks!

**Comment by neeth-kun** [comment]
@Jungwoo-An Thanks a lot! It appears I have made a mistake on my side. The code from your sandbox really helps. Thanks for your response. You saved my day!

**Comment by Jungwoo-An** [comment]
Have a nice day! 👍
