### ISSUE TITLE
Image Upload Error

### ISSUE THREAD

**Issue by neeth-kun** [Jungwoo-An/react-editor-js#49]
When I try to drag and drop or Insert a URL, I don't face any issue. When I try to upload an image, i.e., when the upload image window appears, after the selection of the image, an error is shown, saying **Couldn't upload Image. Try Again** 
Does anyone face the same issue? I observed this issue in the example SandBox too.

**Comment by BadmasterY** [comment]
@neeth-kun 
Let's see this [Image](https://github.com/editor-js/image#config-params).

**Comment by Jungwoo-An** [comment]
@neeth-kun  Hi! First of all, thanks for your interest! 👋 

I think @BadmasterY answer will help you.

Thanks!
