### ISSUE TITLE
Link tool error.

### ISSUE THREAD

**Issue by MateuszGroth** [Jungwoo-An/react-editor-js#50]
Hello,

I have had everything set up with the editor, it was working well and then all of  a sudden the link tool stopped working (I did not do any npm updates). I was wondering why it happened. 
Updating packages helped with that by the way, but some console logs started appearing - 
`Editor.js 2.18.0 I18n: section "tools.linkTool" was not found in current dictionary %o`
![image](https://user-images.githubusercontent.com/39166248/85224032-ae28e180-b3c7-11ea-9506-f189c9b4fcaa.png)

Keep in mind that I do have these tools included and they actually work - I can add images etc.

**Comment by neeth-kun** [comment]
I am having the same issue right now. It worked fine till yesterday.

**Comment by Jungwoo-An** [comment]
@MateuszGroth Hi! First of all, thanks for your interest! 👋 

This error is editor-js 2.18.0 new feature ([CHANGELOG](https://github.com/codex-team/editor.js/blob/4cea66f8caadcd3324994798a919d87ce4bccc47/docs/CHANGELOG.md#218)). If you want to hide warning, you need to downgrade editor-js

Thanks!

**Comment by MateuszGroth** [comment]
Hello. 
Thank you for the answer.

The weird part is that I was using 2.18 from the beginning and there was no consolelogs before this Sunday.  Maybe it has to do something with this warning - 
" `blocks.stretchBlock()` method is deprecated and will be removed in the next major release. Use BlockAPI interface instead "
It came up with the previously mentioned warnings.
(Downgrading raises another issues - image and header tools are not working, so i rather stick with the newest version :P)

Thanks again

**Comment by Jungwoo-An** [comment]
@MateuszGroth 

Hi! If you want to use latest version, set [i18n options](https://editorjs.io/i18n-api).

Thanks again.
