### ISSUE TITLE
Embed Error

### ISSUE THREAD

**Issue by neeth-kun** [Jungwoo-An/react-editor-js#51]
![embed_error](https://user-images.githubusercontent.com/65492441/85423506-65725380-b594-11ea-90b5-acd0598ab73d.png)
The embed feature doesn't have any specific config, but I don't know why this is happening. I didn't have this issue previously. I don't know if this is a specific react editor issue or embed package issue. Can anyone recreate this error in their code? I uninstalled and installed the packages but of no use. The display is getting distorted. Is there any way to resolve this?

**Comment by Jungwoo-An** [comment]
@neeth-kun  Sorry for the slow response and thanks for your interest 👋 

Do you have place where I could reproduce? (ex: CodeSandbox)

**Comment by neeth-kun** [comment]
I am not able to produce it on Sandbox. Also, when I use a list feature, the points are not being visible. Is this because of the update? How do I downgrade it? I added the i18n attribute, but it still shows, can't find tools.embed or tools.header. What might be the problem?

**Comment by Jungwoo-An** [comment]
@neeth-kun 

Did you check CSS? If you want downgrade, just reinstall by specify version. (npm install package@^#.#.#)

**Comment by Jungwoo-An** [comment]
Can you show me the code including i18n option?
