### ISSUE TITLE
Indentation support 

### ISSUE THREAD

**Issue by aliogaili** [Jungwoo-An/react-editor-js#55]
Beautiful editor. 

Is there support for indentation in lists?

**Comment by Jungwoo-An** [comment]
@aliogaili Hi! First of all, thanks for your interest! 👋 

Nested list is not implemented yet. But I think it's future feature. ([Rel](https://github.com/editor-js/list/issues/16))

Thanks!

**Comment by aliogaili** [comment]
I will close since this is requested here https://github.com/editor-js/list/issues/16
