### ISSUE TITLE
readonly mode

### ISSUE THREAD

**Issue by serg-kan** [Jungwoo-An/react-editor-js#56]
Hey!

Your component is just amazing. 
One thing I wanted to ask, is there a way to make the text read only?

I want to use the editor in a blog app, so that one user can write a post, but other people can just read it.

Thanks in advance!

**Comment by Jungwoo-An** [comment]
@serg-kan Hi! First of all, thanks for your interest! 👋 

This issue is same as #19.

Thanks!
