### ISSUE TITLE
Problem with LinkInlineTool

### ISSUE THREAD

**Issue by VLZH** [Jungwoo-An/react-editor-js#6]
By default in `editor.js` tool with name `link` is `LinkInlineTool`, but in this lib the tool `link` is `LinkTool` and i cant to use `LinkInlineTool`.

**Comment by Jungwoo-An** [comment]
@VLZH Thanks to your interest! 🎉

I'm sorry for the inconvenience 😭 i will fix it and update it quickly.

**Comment by Jungwoo-An** [comment]
Hi! you can use `LinkTool` by `linkTool` after update package version v1.3.4! 😍

Thanks!

**Comment by VLZH** [comment]
Thank you for so fast fix)😉
