### ISSUE TITLE
set a placeholder for each element

### ISSUE THREAD

**Issue by serg-kan** [Jungwoo-An/react-editor-js#60]
Hello!

Is it possible to pass a placeholder for a certain element? I saw your explanation [here](https://github.com/codex-team/editor.js/issues/606) and I was able to set a default placeholder.

But what I mean is:

1) I have header-level1 and a paragraph by default
![image](https://user-images.githubusercontent.com/52253662/88225795-c49ab500-cc73-11ea-8917-c74a7cb9906f.png)

2) I want this FIRST header-level1's placeholder to be "Title..." and this certain paragraph's to be "Your text..." for example
something like this:
![image](https://user-images.githubusercontent.com/52253662/88225845-daa87580-cc73-11ea-9773-c0c874db7a82.png)

Hope you got what I mean.
Thank you!

**Comment by Jungwoo-An** [comment]
@serg-kan Hi! First of all, thanks for your interest! 👋 

Unfortunately, it's not yet implemented. 😢 If you want new feature, create issue to editor-js repository.


Thanks!
