### ISSUE TITLE
upload photo with apollo

### ISSUE THREAD

**Issue by sasa6277** [Jungwoo-An/react-editor-js#61]
i can't find any way to upload photo with apollo server ,how can i do that?

**Comment by Jungwoo-An** [comment]
@sasa6277 Hi! First of all, thanks for your interest! 👋 

In my opinion, You should implement [custom uploader function](https://github.com/editor-js/image#providing-custom-uploading-methods).

Thanks!

**Comment by sasa6277** [comment]
thank u friend ,
sorry about say hi.
سلام،HI،درود
