### ISSUE TITLE
Error when deleting block

### ISSUE THREAD

**Issue by ahmad-medhat** [Jungwoo-An/react-editor-js#65]
Hello,
Thank you for your amazing work <3

I installed the plugin and when testing to delete a block, I receive the following error:
n.closest is not a function

I tried the demo and I found the same issue:
https://codesandbox.io/embed/react-editor-js-23opz

Sometimes it appears and somtimes it doesn't.

**Comment by Jungwoo-An** [comment]
@ahmad-medhat Hi! First of all, thanks for your interest! 👋 

It's editor-js error. Can you try to update of editor?

Thanks!
