### ISSUE TITLE
Failed to minify the code from this file.

### ISSUE THREAD

**Issue by kyryloren** [Jungwoo-An/react-editor-js#66]
When I try to run `npm run build` in my react app, I get the following error:

```
Failed to minify the code from this file: 

        ./node_modules/@editorjs/editorjs/dist/editor.js:2:255717 

Read more here: http://bit.ly/2tRViJ9
```

Can you update to fix this issue or can you give me a temporary fix for now?

**Comment by Jungwoo-An** [comment]
@kyryloren Hi! First of all, thanks for your interest! 👋 

Can you give me a reproduce link?

Thanks!
