### ISSUE TITLE
enableReInitialize not working

### ISSUE THREAD

**Issue by sabbyt** [Jungwoo-An/react-editor-js#71]
Currently on `componentDidMount`, updating data prop with previously saved data from API. Set `enableReInitialize` to true but the previously saved data is not showing in the editor.
```
<Editor
enableReInitialize={true}
holder='editorjs'
onData={(data) => this.setState({ data })}
data={this.state.data} /> 
```
Is there a certain format that data should be passed back? Should be able to set the same as previous? I'm saving the initial data format and not changing / re-formatting it.

**Comment by Jungwoo-An** [comment]
@sabbyt Hi! First of all, thanks for your interest! 👋 

I'm sorry for the late reply. I think problem is onData prop. By default, onData is unsupported prop.

Thanks!

**Comment by Jungwoo-An** [comment]
@sabbyt Data fetch code must be wrote in componentDidMount. If you don't mind, give me a reproduce link (CodeSandbox, blitz, ...)
