### ISSUE TITLE
Does not work with next js when tools are added

### ISSUE THREAD

**Issue by StarAzure** [Jungwoo-An/react-editor-js#72]
The solution to use dynamic imports worked for react-editor-js but when I load the tools, it has the same error as in issue before. Please fix this.

https://github.com/Jungwoo-An/react-editor-js/issues/31

Error is `TypeError: Cannot read property 'holder' of undefined`

Here is my code:
```
import dynamic from 'next/dynamic';

const EditorJS = dynamic(
  () => import('react-editor-js'),
  { ssr: false }
)
const Header = dynamic(
  () => import('@editorjs/header'),
  { ssr: false }
)
const Embed = dynamic(
  () => import('@editorjs/embed'),
  { ssr: false }
)
const Table = dynamic(
  () => import('@editorjs/table'),
  { ssr: false }
)
const Paragraph = dynamic(
  () => import('@editorjs/paragraph'),
  { ssr: false }
)


const EDITOR_JS_TOOLS = {
  header: Header,
  embed: Embed,
  table: Table,
  paragraph: Paragraph,
}

  useEffect(() => {
    setEditorTools(EDITOR_JS_TOOLS)
  }, []);
```

and for editor

DOES NOT WORK
`<EditorJS tools={editorTools}/>`

WORKS
`<EditorJS />`

**Comment by Jungwoo-An** [comment]
@StarAzure Hi! First of all, thanks for your interest! 👋 

editor-js tools can't be dynamic at initialization. Here is my example code.

```ts
async loadTools() {
  return Promise.all([import('@editorjs/header'), ...]);
}

const [Header, ...] = await loadTools();

<EditorJS
  tools={{
    header: Header,
  }}
/>
```

Thanks!

**Comment by StarAzure** [comment]
@Jungwoo-An Thanks for looking into this. I followed your suggestion but still get same error.

I created a codesandbox so you can see it yourself - https://codesandbox.io/s/nextjs-forked-qs29j?file=/Hello.js

**Comment by Jungwoo-An** [comment]
@semantic-release-bot Example code is just inspiration. If using dynamic import in nextjs, I think it should be shape below.

```ts
import dynamic from 'next/dynamic';

const Editor = dynamic(
  async () => {
    const [Header] = await Promise.all(
      [
        import('@editorjs/header')
      ].map(promise => promise.then(tool => tool.default)) // ES module
    );

    const ReactEditorJS = await import('react-editor-js').then(editor => editor.default);

    function Component(props) {
      return (
        <ReactEditorJS tools={{ header: Header }} {...props} />
      );
    }

    return {
      default: Component
    };
  },
  {
    ssr: false,
  },
);
```

[Here's example of using React.lazy](https://codesandbox.io/s/react-editor-js-forked-8ts3w?file=/index.js)

**Comment by StarAzure** [comment]
Thanks. 

I also figured out another solution

import {Header, Embed, Table} from '../editorJS/noSSR/NOSSRComponent';

and in NOSSRComponent

```
let Header = '';
let Embed = '';
let Table = '';
if (typeof window !== 'undefined') {
    Header = require('@editorjs/header');
    Embed = require('@editorjs/embed');
    Table = require('@editorjs/table');
}
export {Header, Embed, Table};
```
Appreciate the responses.

**Comment by Jungwoo-An** [comment]
@StarAzure If code splitting is not required, it is fine. But i recommend no-ssr component.

```ts
function NoSSR({ children }) {
  const [canRender, setCanRender] = React.useState(false);

  useEffect(() => {
    setCanRender(true);
  });

  return (
    {canRender ? null : children}
  );
}
```

**Comment by abhik-b** [comment]
Thanks to StarAzure and Jungwoo-An , it's working for me 🙏

**Comment by Rahulkr204** [comment]
@abhik-b Can you share codesandbox or code snippet here. I'm stuck with this issue. It'd of great help.
TIA

**Comment by hatchli** [comment]
Would you please share more working code? The examples you are giving don't make much sense. Where exactly would you integrate the NoSSR function @Jungwoo-An ? Did you mix it with @StarAzure 's "NOSSRComponent"? If you could possible share a codesandebox of this working with Next.js, I would be eternally grateful.

**Comment by abhik-b** [comment]
> @abhik-b Can you share codesandbox or code snippet here. I'm stuck with this issue. It'd of great help.
> TIA

Hi Rahul, Actually I had another issue when I try to unmount this editor which I could not fix so I did not use this editor at all,

However what I did was

1.  create a component(CustomComonent) where I had the editor js and tools
2.  inside the page where I want to render the CustomComponent:

`import dynamic from "next/dynamic";

export default function Page() {

  const DynamicComponentWithNoSSR = dynamic(
    () => import("../../components/CustomComponent"),
    { ssr: false }
  );

  return (
    <div>
      <DynamicComponentWithNoSSR />
    </div>
  );
}`
