### ISSUE TITLE
How to save the editing data on react state? 

### ISSUE THREAD

**Issue by hankyeolk** [Jungwoo-An/react-editor-js#73]
I really appreciated to your work. 
One thing I really want to know is, the way to save edited articles. I want to save the things, which is written on react-editor, on react's state. If you don't mind, please teach me about save the article on react state.

한글로도 이슈를 남깁니다.
우선 editor.js를 리액트에서 편리하게 사용할 수 있게 제공해주셔서 정말 감사합니다.
제가 현재 react-editor를 작은 프로젝트에 반영해보려고 하는데, 에디터에서 작성된 내용물을 state로 관리하여 서버와 데이터를 통신할 수 있는 방법이 정말 궁금합니다. 실례가 되지 않는다면 해당 방법이 있을지, 아니면 서버와 통신하는 방법이 따로 있는지에 대해서 알려주시면 정말 감사할 것 같습니다. 

읽어주셔서 정말 감사합니다.

**Comment by Jungwoo-An** [comment]
@hankyeolk 안녕하세요! 먼저, 관심 가지고 이슈를 남겨주셔서 감사합니다. 이 저장소에서는 한국인분을 처음 뵙는지라, 설레기도 하고 신기하기도 하네요 ㅋㅋㅋ 👍 

일반적으로 데이터 저장 정책에 따라 어떻게 서버에 저장할지가 나뉘게 됩니다. 아래는 각 방법에 대한 설명이고, 서버와 통신할 때는 axios 같은 isomorphic 한 라이브러리를 사용하시면 좋습니다! (가장 많이 사용되는 라이브러리이기도 합니다 😄 )

참고: 아래 2가지 예제에서 모두 에디터의 데이터를 state 로 가지고 있지 않는데, 이유는 react-editor-js 가 기본적으로 [uncontrolled component](https://ko.reactjs.org/docs/uncontrolled-components.html) 로 만들어져 있기 때문입니다.

1. 백그라운드에서 자동 저장
    - 일반적으로 이런 자동 저장은, 유저의 타이핑 이벤트를 [디바운싱](https://medium.com/@pks2974/throttle-%EC%99%80-debounce-%EA%B0%9C%EB%85%90-%EC%A0%95%EB%A6%AC%ED%95%98%EA%B8%B0-2335a9c426ff)하는 방식을 통해서 구현됩니다. 또는 setInterval 을 통해서 특정 주기마다 저장하는 방식을 사용하기도 있지만, 데이터 수정이 없어도 불 필요한 요청이 오고 가기 때문에 반드시 필요한 경우가 아니라면 추천드리지 않습니다.
    - editor-js 에서는 onChange 이벤트가 이미 전자의 방식을 채택하여 구현되어 있습니다. 때문에 onChange 이벤트를 받아서, 서버에 요청하기만 하면 됩니다.

        ```tsx
        function handleChange(newData) {
          axios.post('/save', newData);
        }

        <ReactEditorJS onChange={handleChange} />
        ```
2. 유저의 행동에 의해서 저장 (주로 저장 버튼 클릭)
    - instanceRef 를 통해서 인스턴스를 저장하고, 유저가 저장 버튼을 눌렀을 때 서버에 요청하는 방식으로 구현하면 됩니다.
    - 이 방식은 [Demo](https://codesandbox.io/s/react-editor-js-5d4tu) 에 동일하게 구현되어 있습니다. handleSave 함수에서 axios 를 통해 서버에 요청하면 됩니다.

(위에 작성된 예제들은 실제 코드를 작성할 때 영감을 줄뿐, 제대로 동작하지 않을 수 있음을 참고 부탁드립니다.)

궁금하신 부분이 조금 추상적으로 되어 있어서, 제가 이해한대로 답변을 달기는 했는데.. 혹시 원하시는 답변이 아니라면 궁금하신 부분을 조금 더 자세하게 적어주시면 다시 답변드릴 수 있을 것 같습니다!

감사합니다!

**Comment by hankyeolk** [comment]
상세한 답변 정말 감사합니다. 👍🏼
저는 현재 비전공생으로 개발자로의 전직을 희망하면서 열심히 공부중에 있는 학생입니다.
에디팅 기능이 기반이 되는 리액트 프로젝트를 진행하고 있는 찰라에 작성자님이 정리해주신 editor.js 리액트 버전을 알게 되었습니다.

제안해주신 2가지의 답변 중에서 우선적으로는 2번에 해당하는 instanceRef 방식을 먼저 해보려고 합니다. 정말 많은 도움을 받았습니다. 작업을 계속 진행하면서 이슈 사항이 생긴다면 오늘과 같이 소통할 수 있으면 좋을 것 같습니다. 

정말 감사합니다. 날씨가 부쩍 추워졌는데 감기 조심하세요 😀

**Comment by Jungwoo-An** [comment]
열의가 대단하시네요. 👍🏻 뭐든 잘 하실 것 같습니다.

언제든지 궁금하신 부분에 대해서는 여기 이슈로 달아주셔도 좋고, 메일로 보내주시면 아는선에서 도움드릴 수 있을 듯 합니다. (제 메일 주소는 프로필에 있습니다 😃)

한결님도 감기 조심하시고, 좋은 하루되시길 바라요. 응원하겠습니다!

감사합니다.
