### ISSUE TITLE
How to wrap a simple editorJs plugin around a react component such as material ui Alert?

### ISSUE THREAD

**Issue by StarAzure** [Jungwoo-An/react-editor-js#74]
How to wrap editor js text around a react component such as material ui Alert ?

Something like:

`<Alert severity="error">This is the text entered in editor JS</Alert>`

```
import Alert from '@material-ui/lab/Alert';

    class Alert {
      static get toolbox() {
        return {
          title: 'Image',
          icon: 'SomeSVG'
        };
      }
    
      render(){
        return document.createElement('input');
      }
    
      save(blockContent){
        return {
          url: blockContent.value
        }
      }
    }
```

**Comment by Jungwoo-An** [comment]
@StarAzure Hi! First of all, thanks for your interest! 👋 

I don't recommend create plugin with react component. Nevertheless if you want to create plugin, look at [this issue](https://github.com/Jungwoo-An/react-editor-js/issues/69)

Thanks!

**Comment by Jungwoo-An** [comment]
@StarAzure I'm sorry for the late reply 😢 ..

I think you should add material-ui css style to global, but if importable external css file does not exist, there is no way to create plugin. 😞 (for example, framework that use css in js).

If you need simple alert, find the solution outside of editor-js.

**Comment by StarAzure** [comment]
Thanks much
