### ISSUE TITLE
When the page hot reloads, I get this error: Cannot read property 'deactivate' of null

### ISSUE THREAD

**Issue by Bonjur** [Jungwoo-An/react-editor-js#78]
`editor.js?9336:2 Uncaught (in promise) TypeError: Cannot read property 'deactivate' of null
    at o.value (editor.js?9336:2)
    at o.value (editor.js?9336:2)
    at eval (editor.js?9336:2)
    at Array.forEach (<anonymous>)
    at t.destroy (editor.js?9336:2)
    at eval (react-editor-js.es.js:22)
    at eval (scheduler.js?f1c4:10)
    at batchedUpdates$1 (react-dom.development.js?61bb:21856)
    at batch (scheduler.js?f1c4:10)
    at batched (scheduler.js?f1c4:25)`

How to stop it being destroyed?
onReady=(()=>{?})

**Comment by Jungwoo-An** [comment]
@Bonjur Hi! First of all, thanks for your interest! 👋 

react-editor-js is destroy editor-js instance when componentWillUnmount. I think that's issue of editor-js library. 😢 Can you provide me reproduce link? (Github, Codesandbox, ...)

Thanks!

**Comment by adshin21** [comment]
@Bonjur Hello, so I've also encountered the same issue and the root for this is the latest version of editorjs, but didn't find the solution

**Comment by JANDA-Developers** [comment]
We can use destory Method thorugh instanceRef  to avoid SSR issue i am currently using this code 
`let EDITR: any = null;
export const Editor: React.FC<IProp> = (props) => {
    const [editorTools, setTools] = useState<any>(undefined);

    useEffect(() => {
        const fetch = async () => {
            const editorTools = (await import('components/editor/tools.js')).default;
            setTools(editorTools);
        }

        fetch()
    }, [])


    useEffect(() => {
        () => {

            EDITR.destory();

        }
    })

    if (!editorTools) {
        return <div />
    }

    return <EditorJs instanceRef={ins => EDITR = ins} {...props} tools={editorTools} />;
};
`

**Comment by Jungwoo-An** [comment]
@adshin21 @Bonjur Related issue https://github.com/codex-team/editor.js/issues/1400

**Comment by SuperWallaby** [comment]
Personally I am struggling with same issue.. Just wanna say thank everyone who works here. and Cheer Up!!!

**Comment by Bonjur** [comment]
> @Bonjur Hello, so I've also encountered the same issue and the root for this is the latest version of editorjs, but didn't find the solution

Yes, coming back to this now, I just reverted to older version.

**Comment by Jungwoo-An** [comment]
This issue has been fixed. should update editor-js version to 2.19.1
