### ISSUE TITLE
inline Marker is not working

### ISSUE THREAD

**Issue by amed** [Jungwoo-An/react-editor-js#8]
First of all, thank you for the react wrapper. 

There is an issue with Marker `@editorjs/marker` simply it does not respond to highlight which is not expected (tested on both Chrome & Firefox latest versions).
The [provided example](https://codesandbox.io/embed/react-editor-js-23opz) have this issue as well.

**Comment by Jungwoo-An** [comment]
@amed Thanks for your interest 😍

it's my fault, i'll check marker tool. sorry!

**Comment by Jungwoo-An** [comment]
@amed Hi! this issue is fix and published! (v1.4.1) 😍

Check it on [codesandbox](https://codesandbox.io/embed/react-editor-js-23opz)

**Comment by miguelangeltorresfp** [comment]
@Jungwoo-An, thank you very much for this wrapper.
I'm using it in next.js but I'm only import it on client side.
Everything seems to work perfectly except the Marker.
It's loaded but doesn't seem to receive the event when I highlight a text and therefore remains hidden.
It doesn't show any error in the console.
Do you have any idea on how to solve this issue ?
I'm using last version of both package:
"react-editor-js": "^1.4.1", 
"@editorjs/marker": "^1.2.1",

**Comment by ngmiduc** [comment]
Cool,
I noticed some werid bugs with the toolbox.
https://codesandbox.io/s/react-editor-js-forked-02g8l?file=/constants.js

I have updated all depencies and the toolbox is not showing up.
It is like sometimes some tools are not working together. 
I am not sure which ones, but for the moment, I only use 1 or 2, to avoid that the toolbox is not visisble.

**Comment by ngmiduc** [comment]
I have issues when using paragraph tool
https://codesandbox.io/s/react-editor-js-forked-02g8l?file=/constants.js:317-336
The toolbox (inline) is not showing up in this case

**Comment by Jungwoo-An** [comment]
@ngmiduc Check [inlineToolbar option](https://github.com/editor-js/paragraph#usage) of paragraph tool. 🙏🏻
