### ISSUE TITLE
react-editor-js wrapper is different from original repo

### ISSUE THREAD

**Issue by mustafat0k** [Jungwoo-An/react-editor-js#80]
I using multiple editors but when i typing a text it's disappearing. I can't get it back with CTRL+Z unfortunately. Totaly different from original repo as ui and effects.
When i select a word  doesnt there tools just  i can add a  new block.    
Doesn't show  toolbar (b,i,u) and there have more similar issues. Original repo is working properly and UI is different from this repo. Useless as it is! Maybe you want to interest to fix those. 
Some console.error like `Uncaught TypeError: Cannot read property 'parentNode' of null`  or `Cannot read property 'updateCurrentInput' of undefined` 
Some times this errors going to hundreds i tried MANY ways but very problematic. I dont even count packages versioning problems.

Note: I switched ckeditor ballon plugin.

**Comment by Jungwoo-An** [comment]
@mustafat0k Hi! First of all, thanks for your interest! 👋 

Can you provide me reproduce link? (Github, Codesandbox, ...)

Thanks!
