### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by Gaboik** [Jungwoo-An/react-editor-js#81]
On npm, the package is listed as MIT but IMO it's unclear whether this license applies only to the 'compiled' code or if it applies to the source code held in this Git repository as well, please, provide a license for this repository so we know what we can and cannot do using the source code of this repository!

Thanks!

**Comment by Jungwoo-An** [comment]
@Gaboik Hi! First of all, thanks for your interest! 👋 

I'll add LICENSE file asap.

Thanks!

**Comment by Jungwoo-An** [comment]
@Gaboik Thank you for your suggestion. 🙌🏻 I merged #84.
