### ISSUE TITLE
Editor.js linktools is not working 

### ISSUE THREAD

**Issue by TalentFlow** [Jungwoo-An/react-editor-js#82]
Whenever is enter a link, it says:"Couldn't get this link data, try the other one".
Whereas in editor.js official page, its working.

https://user-images.githubusercontent.com/75980661/103643954-5a52a400-4f77-11eb-926f-88720d51effe.mp4

**Comment by TalentFlow** [comment]
@Jungwoo-An @jakekara @VLZH @marianrick Can you please guide me

**Comment by marianrick** [comment]
First things first: I am no expert for react editor js and have no idea.

Second: I think you will have to provide more information (for example the console output or other logs) to receive help 🙂

**Comment by Jungwoo-An** [comment]
@TalentFlow Hi! First of all, thanks for your interest! ❤️ 

Please read this [document](https://github.com/Jungwoo-An/react-editor-js#havent-received-data-from-server-when-use-link) 🙌🏻 . I think you should set linkTool config. 🙇 

Thanks!

**Comment by SohaibShafiq1** [comment]
@Jungwoo-An But i want frontend fetching url
![Annotation 2021-01-06 220417](https://user-images.githubusercontent.com/57568754/103798163-2658ab00-506b-11eb-901e-f591e948c950.jpg)

**Comment by Jungwoo-An** [comment]
@SohaibShafiq1 You can use simple-image instead of image. 🙏
