### ISSUE TITLE
Editor.js is not ready because of TypeError: Cannot create property 'blocks' on string

### ISSUE THREAD

**Issue by SohaibShafiq1** [Jungwoo-An/react-editor-js#85]
@Jungwoo-An @VLZH @jakekara @marianrick
Whenever i load data from server. I got this error:
Editor.js is not ready because of TypeError: Cannot create property 'blocks' on string '{"time":1609871884879,"blocks":[{"type":"paragraph","data":{"text":"knkcncklancaklsncalkc"}},{"type":"paragraph","data":{"text":"knlkelwkelkenflk"}}],"version":"2.13.0"}' 
Uncaught (in promise) TypeError: Cannot create property 'blocks' on string '{"time":1609871884879,"blocks":[{"type":"paragraph","data":{"text":"knkcncklancaklsncalkc"}},{"type":"paragraph","data":{"text":"knlkelwkelkenflk"}}],"version":"2.13.0"}'
I also perform many Parsers, html decoder to convert it into html but attempts sucks.
Can you help me.
![Annotation 2021-01-06 170754](https://user-images.githubusercontent.com/57568754/103767063-c13c8f80-5041-11eb-96cf-9ffec3c3508a.jpg)

**Comment by Jungwoo-An** [comment]
@SohaibShafiq1 Hi! First of all, thanks for your interest! 👋 

Can you show me your server response?

Thanks!

**Comment by SohaibShafiq1** [comment]
![Uploading Annotation 2021-01-06 182229.jpg…]()

**Comment by SohaibShafiq1** [comment]
![Annotation 2021-01-06 182229](https://user-images.githubusercontent.com/57568754/103773187-7d02bc80-504c-11eb-86d1-6bd0d22f2328.jpg)

**Comment by SohaibShafiq1** [comment]
This my code in react.js
![Annotation 2021-01-06 183024](https://user-images.githubusercontent.com/57568754/103773713-4c6f5280-504d-11eb-8baf-c14734627d17.jpg)

**Comment by SohaibShafiq1** [comment]
> This my code in react.js
> ![Annotation 2021-01-06 183024](https://user-images.githubusercontent.com/57568754/103773713-4c6f5280-504d-11eb-8baf-c14734627d17.jpg)
When i use <EditorJs data={Parse(post.description)} /> it also did not work.

**Comment by SohaibShafiq1** [comment]
I Found the Solution.
the data was in string formate.
JSON.parse makes my day.

**Comment by SohaibShafiq1** [comment]
I Found the Solution.
the data was in string formate.
JSON.parse makes my day.
