### ISSUE TITLE
Simple-Image option did not showing. Is it possible to paste only image Link

### ISSUE THREAD

**Issue by SohaibShafiq1** [Jungwoo-An/react-editor-js#86]
@Jungwoo-An @VLZH @marianrick @jakekara 
![Annotation 2021-01-06 220620](https://user-images.githubusercontent.com/57568754/103798383-6e77cd80-506b-11eb-8aff-73d5ad2ae8e2.jpg)

**Comment by Jungwoo-An** [comment]
@SohaibShafiq1 Hi! Show me your simple-image options.

**Comment by Jungwoo-An** [comment]
@SohaibShafiq1 Hi! First of all, thanks for your interest! 👋 

Can you show me your editor-js tools options?

Thanks!
