### ISSUE TITLE
<Editor/> readOnly property not reactive

### ISSUE THREAD

**Issue by ibrahimyaacob92** [Jungwoo-An/react-editor-js#89]
i have this code below :
![image](https://user-images.githubusercontent.com/58116068/105217237-90567180-5b8e-11eb-8f9e-db77cfd81053.png)

setting setReadOnly to true or false doesnt change anything

**Comment by ibrahimyaacob92** [comment]
this is my workaround.. not so pretty
![image](https://user-images.githubusercontent.com/58116068/105218371-060f0d00-5b90-11eb-91af-c6bf35e86102.png)

**Comment by Jungwoo-An** [comment]
@ibrahimyaacob92 Hi! First of all, thanks for your interest! 👋 

I'll check it asap

Thanks!

**Comment by abbandev** [comment]
I also am dealing with this when I set readOnly to true the editor just hangs and just shows loading

**Comment by Jungwoo-An** [comment]
@ibrahimyaacob92 (@abbandev) I updated readonly mode support (#90) You need to update react-editor-js version to 1.8.0.

Thanks!

**Comment by ibrahimyaacob92** [comment]
works like charm now ! Closing the issue :)

**Comment by abbandev** [comment]
Im still having loading issue and Im on 1.9
