### ISSUE TITLE
logLevel string type warning

### ISSUE THREAD

**Issue by tom2strobl** [Jungwoo-An/react-editor-js#96]
### Environment

- @editorjs/editorjs version: 2.19.1
- react-editor-js version: 1.9.0

### Describe

The library nicely forwards other props through spread, so I can use this to prevent those completely obnoxious logs from editor js:
```jsx
<EditorJs logLevel="ERROR" />
```

For some reason that results in a typescript warning:
```
No overload matches this call.
  Overload 1 of 2, '(props: Props | Readonly<Props>): EditorJsContainer', gave the following error.
    Type '"ERROR"' is not assignable to type 'LogLevels | undefined'.
  Overload 2 of 2, '(props: Props, context: any): EditorJsContainer', gave the following error.
    Type '"ERROR"' is not assignable to type 'LogLevels | undefined'.ts(2769)
editor-config.d.ts(71, 3): The expected type comes from property 'logLevel' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<EditorJsContainer> & Readonly<Props> & Readonly<...>'
editor-config.d.ts(71, 3): The expected type comes from property 'logLevel' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<EditorJsContainer> & Readonly<Props> & Readonly<...>'
```

On https://editorjs.io/configuration#log-level it showcases `"ERROR"` as an example, so that's kinda weird that it's not being picked up. Could it have something to do with `LogLevels` in `@editorjs/editor/types/config/log-levels.d.ts` being an enum?

Do I have to pick up some constant variable instead of the string `'ERROR'` to circumvent the warning?

That being said, it works, just shows the warning, so this issue is of super low importance.

**Comment by Jungwoo-An** [comment]
@tom2strobl Hi! First of all, thanks for your interest! 👋 

I think it should set to enum. ([editor-js types](https://github.com/codex-team/editor.js/blob/next/types/configs/log-levels.d.ts))

Thanks!

**Comment by tom2strobl** [comment]
I actually fixed it by importing the enum
```
import { LogLevels } from '@editorjs/editorjs/types/configs/log-levels'
```
and then using `LogLevels.ERROR` instead of the string `"ERROR"`.

To be honest that their issue and nothing you can/should do to support strings, so I'm closing this issue.
Thanks!
