### ISSUE TITLE
Unable to save image

### ISSUE THREAD

**Issue by beastOP** [Jungwoo-An/react-editor-js#97]
![Screenshot_2021-02-03-00-25-30-43](https://user-images.githubusercontent.com/52950675/106648500-5f2a6800-65b6-11eb-8ccf-c198b7b4aedd.jpg)
how to save uploaded image to state and preview it?

**Comment by Jungwoo-An** [comment]
@beastOP Hi! First of all, thanks for your interest! 👋 

If you are using the image plugin, you must set [uploader](https://github.com/editor-js/image#config-params) config.

Thanks!

**Comment by beastOP** [comment]
@Jungwoo-An thank you for replying, but how should the backend look like what should it return as a response

I followed a steps, 
	my endpoint localhost:8080/upload returns status(200)

still it fails to preview the image

**Comment by Jungwoo-An** [comment]
@beastOP I'm sorry for the late reply. uploader function response must be Promise<{ success: 0 or 1; file: { url: string; }}>. Example is below.

```js
uploader: {
  uploadByFile(file) {
    return Promise.resolve({
      success: 1,
      file: {
        url: '...'
	  }
    });
  }
}
```

**Comment by Isaac-Svi** [comment]
@beastOP 

Hey, I'd just add that it adding a custom uploader function is one way to do it, but you can also upload by setting up an endpoint in your config instead, like this:
```javascript
// all the imports...

const tools = {
  paragraph: Paragraph,
  image: {
    class: ImageTool,
    config: {
      endpoints: {
        byFile: '/api/upload',
      },
    },
  },
}

export default class Editor extends Component {
  render() {
    return (
      <EditorJs
        tools={tools}
        instanceRef={(instance) => (this.editorInstance = instance)}
      />
    )
  }
}
```

In the back end, I'm using multer, and this is what I have:
```javascript
app.post('/api/upload', upload.single('image'), (req, res) => {
  const url = '/api/' + req.file.path.replace(/\\/g, '/')

  res.send({
    success: 1,
    file: {
      url,
    },
  })
})
```
The point is, editor-js sends the image as multipart/form-data with a key of 'image' along a predefined POST route; '/api/upload' is what I called it.  To display the image in the editor right after it's sent, the response needs to be formatted exactly how it is in the example.  There needs to be a success key with 1 or 0, and a file object with a key of url which should contain the url for the newly uploaded image.

If you'd like to see a full working example, you can check out the repo I made to test this out [here](https://github.com/Isaac-Svi/react-editor-js-test).
