### ISSUE TITLE
Having loading issue with readOnly on 1.9

### ISSUE THREAD

**Issue by abbandev** [Jungwoo-An/react-editor-js#98]
Im still having loading issue when readOnly is set to true and Im on 1.9

_Originally posted by @abbandev in https://github.com/Jungwoo-An/react-editor-js/issues/89#issuecomment-767937463_

This loading loop just shows.
![Screen Shot 2021-02-14 at 4 22 44 PM](https://user-images.githubusercontent.com/74944205/107890860-e04ffc00-6ee0-11eb-9fd8-bfd3cc5edbae.png)

**Comment by Jungwoo-An** [comment]
Could you provide me reproduce link? (Github, Codesandbox, ...)

Thanks!

**Comment by abbandev** [comment]
I realized it is because I am getting this exception
`Uncaught (in promise) Error: To enable read-only mode all connected tools should support it. Tools paragraph don't support read-only mode.
    at editor.js:2
    at c (editor.js:2)`

**Comment by Jungwoo-An** [comment]
@abbandev You must update Editor-js and the tools used. To use readonly mode, tools must support readonly mode.
